import test from 'node:test';
import assert from 'node:assert/strict';
import {L,ORDER,UI,setLanguage,tr} from '../src/i18n.js';
import {CHAPTERS,INTROS,RECORDS,CHOICES,ENDINGS,AFTERMATH} from '../src/content.js';
import {newState,validateState,readSave,writeSave,readSettings,chapterDone,addDecision,addEpisodeDecision,advanceChapter,canChooseEnding,reflectionCounts,obstacles,walkable,approachPath} from '../src/state.js';
import {generateCircuit,circuitStatus,rotateMask,generateLights,toggleLights,generateSequence,generateLedger,generateCode} from '../src/puzzles.js';

test('all visible copy is present in all eight locales, with matching variables',()=>{
 let count=0;function visit(value){if(!value||typeof value!=='object')return;if('fa'in value){count++;for(const locale of ORDER){assert.equal(typeof value[locale],'string',`Missing ${locale}: ${value.fa}`);assert.ok(value[locale].trim());assert.deepEqual([...value[locale].matchAll(/\{\w+\}/g)].map(x=>x[0]).sort(),[...value.fa.matchAll(/\{\w+\}/g)].map(x=>x[0]).sort());}return;}for(const child of Object.values(value))visit(child);}visit(UI);visit(CHAPTERS);visit(ENDINGS);assert.equal(count,Object.keys(UI).length+CHAPTERS.reduce((sum,c)=>sum+2+c.records.length+c.choices.length,0)+ENDINGS.length*3);setLanguage('zh');assert.equal(tr('chapters'),'故事章节');setLanguage('fa');assert.equal(tr(L('آزمایش','test','测试','اختبار','prueba','परीक्षा','test','teste')),'آزمایش');
});
test('all eight chapters expose reachable stations, records, people and exits',()=>{
 for(const ch of CHAPTERS){const blocks=obstacles(ch);assert.ok(walkable(ch.start.x,ch.start.y,blocks));assert.equal(ch.entities.filter(e=>e.type==='station').length,3);assert.equal(ch.entities.filter(e=>e.type==='record').length,4);for(const entity of ch.entities){const path=approachPath(ch.start,entity,blocks);assert.ok(path.length,`Unreachable ${entity.id}`);assert.ok(path.every(p=>walkable(p.x,p.y,blocks)),`Blocked path ${entity.id}`);assert.ok(Math.hypot(path.at(-1).x-entity.x,path.at(-1).y-entity.y)<64);}}
});
test('circuit puzzles always have an independently traversable solution and never start solved',()=>{
 for(let seed=1;seed<=100;seed++)for(const size of [4,5,6]){const p=generateCircuit(size,seed);assert.equal(p.tiles.length,size*size);assert.equal(circuitStatus(p.solution,size).solved,true);assert.equal(circuitStatus(p.tiles,size).solved,false);for(const mask of p.solution){let copy=mask;for(let n=0;n<4;n++)copy=rotateMask(copy);assert.equal(copy,mask);}const broken=p.solution.map(()=>0);assert.equal(circuitStatus(broken,size).solved,false);}
});
test('lights puzzles can always be reversed from their scrambled starting state',()=>{for(let seed=1;seed<100;seed++)for(const size of [3,4]){const p=generateLights(size,seed);assert.equal(p.board.every(Boolean),false);for(const move of [...p.solution].reverse())toggleLights(p.board,size,move);assert.ok(p.board.every(v=>v===1));}});
test('ledger, signal and cipher generators remain valid across seeds and stages',()=>{for(let seed=1;seed<100;seed++){const seq=generateSequence(8,seed);assert.equal(seq.length,8);assert.ok(seq.every((n,i)=>n>=0&&n<9&&(i===0||n!==seq[i-1])));const ledger=generateLedger(6,seed);assert.deepEqual([...ledger.right].sort((a,b)=>a.id-b.id),ledger.left);assert.ok(ledger.left.every(e=>e.a+e.b===e.value));for(let round=0;round<3;round++){const p=generateCode(round,seed);assert.equal(p.solution.length,4);assert.ok(p.solution.every(n=>n>=0&&n<=9));}}});
test('progression requires solved stations and a deliberate decision',()=>{const state=newState();assert.equal(advanceChapter(state),false);for(let chapter=0;chapter<7;chapter++){assert.equal(state.chapter,chapter);state.solved.push(...CHAPTERS[chapter].entities.filter(e=>e.type==='station').map(e=>e.id));assert.equal(chapterDone(state,chapter),false);assert.equal(addEpisodeDecision(state,chapter,0),true);assert.equal(chapterDone(state,chapter),true);assert.equal(advanceChapter(state),false);assert.equal(addDecision(state,chapter,chapter%3),true);assert.equal(addDecision(state,chapter,2),false);assert.equal(advanceChapter(state),true);assert.ok(validateState(state));}assert.equal(state.chapter,7);assert.equal(state.unlocked,7);assert.equal(advanceChapter(state),false);});
test('the eight original endings retain their documented requirements',()=>{const s=newState();s.chapter=s.unlocked=7;for(const e of ENDINGS.slice(0,8))assert.equal(canChooseEnding(s,e.id),!['shared','witness','loop'].includes(e.id));s.records=['0:r0','1:r0','2:r0'];s.solved=['7:s0','7:s1','7:s2'];addEpisodeDecision(s,7,0);assert.equal(canChooseEnding(s,'shared'),true);assert.equal(canChooseEnding(s,'witness'),false);s.records=CHAPTERS.slice(0,3).flatMap(c=>c.entities.filter(e=>e.type==='record').map(e=>e.id));addEpisodeDecision(s,6,0);assert.equal(canChooseEnding(s,'witness'),true);addEpisodeDecision(s,0,1);assert.equal(canChooseEnding(s,'loop'),true);s.microDecisions[7]=1;assert.equal(canChooseEnding(s,'shared'),false);assert.equal(canChooseEnding(s,'witness'),false);assert.equal(canChooseEnding(s,'bad-id'),false);});
test('save round trips and rejects corrupted or hostile imports',()=>{const store=new Map(),storage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},s=newState();assert.equal(writeSave(storage,s),true);assert.deepEqual(readSave(storage),s);for(const patch of [{chapter:8},{chapter:-1},{unlocked:-1},{solved:['injected']},{records:['0:s0']},{decisions:{0:5}},{position:{x:Infinity,y:0}},{playSeconds:-1},{ending:'undefined'}])assert.equal(validateState({...s,...patch}),null);assert.equal(writeSave({setItem:()=>{throw new Error('quota');}},s),false);assert.equal(readSave({getItem:()=>'{bad'}),null);assert.equal(readSettings({getItem:()=>'{bad'}).language,'fa');});
test('assistance, speed, language and retries never enter reflective observations',()=>{const a=newState();addDecision(a,0,0);addDecision(a,1,0);const before=reflectionCounts(a);a.playSeconds=4567;a.puzzleProgress={'0:s0':3};a.solved=['0:s0'];a.records=['0:r0'];assert.deepEqual(reflectionCounts(a),before);assert.deepEqual(before,{accountable:1,evidence:1,consent:1});});
test('earlier choices yield localized narrative consequences; leaving is possible from the start',()=>{for(const variant of Object.values(AFTERMATH))for(const locale of ORDER)assert.ok(typeof variant[locale]==='string'&&variant[locale].length>20);const s=newState();assert.equal(canChooseEnding(s,'leave'),true);assert.equal(canChooseEnding(s,'repayment'),false);addDecision(s,0,0);assert.equal(reflectionCounts(s).accountable,1);const alternative=newState();addDecision(alternative,0,1);assert.equal(reflectionCounts(alternative).accountable,undefined);});
