import {chromium} from 'playwright-core';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:960},deviceScaleFactor:1});
const page=await context.newPage(),errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)requests.push(r.url()+': '+r.status());});
try{
 await page.goto('http://localhost:4173',{waitUntil:'networkidle'});
 await page.locator('#new-game').waitFor();
 assert.equal(await page.locator('html').getAttribute('lang'),'fa');
 await page.screenshot({path:'artifacts/title-fa-desktop.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false);
 await page.locator('#new-game').click();
 await page.locator('#modal-content .btn.primary').click();
 await page.locator('#modal-content .btn.primary').click();
 await page.locator('#world').focus();
 await page.keyboard.down('ArrowRight');await page.waitForTimeout(900);await page.keyboard.up('ArrowRight');
 await page.screenshot({path:'artifacts/game-fa-desktop.png',fullPage:true});
 await page.locator('#journal').click();
 assert.ok((await page.locator('#modal-content').innerText()).includes('دفترچه'));
 await page.keyboard.press('Escape');
 await page.locator('#settings').click();
 await page.locator('#modal-content select').first().selectOption('zh');
 assert.equal(await page.locator('html').getAttribute('lang'),'zh-Hans');
 await page.screenshot({path:'artifacts/settings-zh-desktop.png',fullPage:true});
 await page.keyboard.press('Escape');
 await page.reload({waitUntil:'networkidle'});
 assert.equal(await page.locator('html').getAttribute('lang'),'zh-Hans');
 assert.equal(await page.locator('#continue-game').isVisible(),true);
 await page.locator('#continue-game').click();
 await page.screenshot({path:'artifacts/game-zh-desktop.png',fullPage:true});
 // A fresh isolated context exercises real touch events and Persian default settings.
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
 const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push('mobile: '+e.message));
 await phone.goto('http://localhost:4173',{waitUntil:'networkidle'});
 await phone.screenshot({path:'artifacts/title-fa-mobile.png',fullPage:true});
 assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await phone.locator('#new-game').tap();await phone.locator('#modal-content .btn.primary').tap();await phone.locator('#modal-content .btn.primary').tap();
 assert.equal(await phone.locator('#touch-controls').isVisible(),true);
 await phone.locator('#touch-ward').tap();
 assert.equal(await phone.locator('#touch-ward').isDisabled(),true);
 assert.equal(await phone.locator('#touch-run').isVisible(),true);
 await phone.locator('[data-dir="up"]').tap();
 await phone.screenshot({path:'artifacts/game-fa-mobile.png',fullPage:true});
 assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await phone.locator('#settings').tap();
 await phone.locator('#modal-content select').first().selectOption('ar');
 assert.equal(await phone.locator('html').getAttribute('dir'),'rtl');
 await phone.screenshot({path:'artifacts/settings-ar-mobile.png',fullPage:true});
 await mobile.close();
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 await writeFile('artifacts/browser-smoke.json',JSON.stringify({passed:true,desktop:'1440x960',mobile:'390x844, touch emulation',errors,requests},null,2));
 console.log('Browser smoke passed: Persian start, actual keyboard input, Chinese switching, resume, touch layout, Arabic RTL, no console or HTTP errors.');
}finally{await browser.close();}
