import { L } from './i18n.js';
import {applyLayout} from './level-layouts.js';
import {EXTRA_ENDINGS} from './episodes.js';
import {NEW_ENDINGS} from './ending-content.js';
export const TITLES=[
L('مغازه‌ای که فردا خالی می‌شود','The shop that closes tomorrow','明天关闭的小店','المتجر الذي يغلق غداً','La tienda que cierra mañana','कल बंद होने वाली दुकान','La boutique qui ferme demain','A loja que fecha amanhã'),
L('دست اول','The first hand','最初的手','اليد الأولى','La primera mano','पहला हाथ','La première main','A primeira mão'),
L('فاصلهٔ میان دو دست','The distance between two hands','双手之间的距离','المسافة بين يدين','La distancia entre dos manos','दो हाथों के बीच की दूरी','La distance entre deux mains','A distância entre duas mãos'),
L('خانهٔ کاغذی','The paper house','纸屋','البيت الورقي','La casa de papel','काग़ज़ का घर','La maison de papier','A casa de papel'),
L('نام مستعار','The pseudonym','化名','الاسم المستعار','El seudónimo','उपनाम','Le pseudonyme','O pseudônimo'),
L('دو پیتزا','Two pizzas','两张披萨','قطعتا بيتزا','Dos pizzas','दो पिज़्ज़ा','Deux pizzas','Duas pizzas'),
L('اتاق تسویه','The clearing room','清算室','غرفة التسوية','La sala de compensación','निपटान कक्ष','La chambre de compensation','A sala de compensação'),
L('آخرین خریدار','The last buyer','最后的买家','المشتري الأخير','El último comprador','आख़िरी खरीदार','Le dernier acheteur','O último comprador')];
export const INTROS=[
L('پنج سال از آن صبح گذشته. فردا مینا ابزارهایش را می‌برد. تو مانده‌ای تا رایانه‌ها را پاک کنی. یک نمایشگرِ بی‌برق روشن می‌شود: «جبران زیان امکان‌پذیر است. گذشته قابل‌تغییر نیست.» اول برق، آرشیو و پیام تلفن را بررسی کن.','Five years since that morning. Tomorrow Mina takes her tools. You stayed to erase the computers. An unplugged screen lights up: “Loss can be repaid. The past cannot be changed.” Check the power, archive and phone.','那个早晨已经过去五年。明天米娜会带走工具。你留下清理电脑。一台未接电的屏幕亮起：“损失可以偿还，过去无法改变。”检查电源、档案与电话。','مرت خمس سنوات على ذلك الصباح. غداً تأخذ مينا أدواتها. بقيت لمسح الحواسيب. تضيء شاشة مفصولة: «يمكن تعويض الخسارة. لا يمكن تغيير الماضي». افحص الكهرباء والأرشيف والهاتف.','Han pasado cinco años. Mañana Mina se lleva sus herramientas. Una pantalla desenchufada se enciende: «La pérdida puede repararse. El pasado no puede cambiarse». Revisa la corriente, el archivo y el teléfono.','उस सुबह को पाँच वर्ष हुए। कल मीना अपने औज़ार ले जाएगी। बिना बिजली वाली स्क्रीन जलती है: «नुकसान चुकाया जा सकता है। अतीत नहीं बदलता।» बिजली, अभिलेख और फ़ोन जाँचें।','Cinq ans ont passé. Demain, Mina emporte ses outils. Un écran débranché s’allume : «La perte peut être remboursée. Le passé ne peut être changé.» Vérifiez le courant, les archives et le téléphone.','Cinco anos se passaram. Amanhã Mina leva suas ferramentas. Uma tela desligada acende: “A perda pode ser paga. O passado não pode mudar.” Verifique a energia, o arquivo e o telefone.'),
L('تاریخ روی در پاک شده: «زمان و مکان نامعلوم؛ بازسازی خیالی». زنی غله دارد و مردی تیغه‌ای ترک‌خورده. پیش از قیمت‌گذاشتن، ببین چه چیزی را نمی‌دانی. سه بخش رسید را کامل کن.','The date has vanished: “Time and place unknown; fictional reconstruction.” A woman holds grain. A man holds a cracked blade. Before setting a price, discover what you do not know. Reconstruct the receipt.','日期消失了：“时间地点未知，虚构重建。”女人抱着谷物，男人拿着有裂痕的刀。定价前，先了解未知。修复收据的三个部分。','اختفى التاريخ: «الزمان والمكان مجهولان؛ بناء خيالي». امرأة تحمل حبوباً ورجل يحمل شفرة مشقوقة. اكتشف ما تجهله قبل التسعير. أكمل أجزاء الإيصال.','La fecha ha desaparecido: «Lugar y época desconocidos; reconstrucción ficticia». Una mujer tiene grano; un hombre, una hoja agrietada. Descubre lo que ignoras antes de fijar un precio. Reconstruye el recibo.','तारीख मिट गई: «समय और स्थान अज्ञात; काल्पनिक पुनर्रचना।» एक स्त्री के पास अनाज, एक पुरुष के पास टूटा औज़ार है। दाम लगाने से पहले अज्ञात बातों को जानें। रसीद पूरी करें।','La date a disparu : «Lieu et époque inconnus ; reconstitution fictive.» Une femme tient du grain, un homme une lame fissurée. Avant de fixer un prix, découvrez ce que vous ignorez. Reconstituez le reçu.','A data desapareceu: “Lugar e época desconhecidos; reconstrução fictícia.” Uma mulher tem grãos; um homem, uma lâmina rachada. Descubra o que ignora antes de definir um preço. Reconstrua o recibo.'),
L('یک بسته باید از راهروی تاریک عبور کند. فرستنده منتظر پول است؛ خریدار منتظر مدرک. مسیر، امضا و دو نسخهٔ رسید را بررسی کن. سایه حالا دنبال دست‌های تو می‌گردد.','A parcel must cross a dark corridor. The sender waits for payment; the buyer waits for proof. Verify the route, signature and both receipts. The shadow is now looking for your hands.','包裹必须穿过黑暗走廊。卖家等待付款，买家等待证据。验证路线、签名与两份收据。影子开始寻找你的双手。','يجب أن تعبر حزمة ممراً مظلماً. المرسل ينتظر المال والمشتري ينتظر الدليل. تحقق من الطريق والتوقيع والإيصالين. الظل يبحث الآن عن يديك.','Un paquete debe cruzar un pasillo oscuro. El vendedor espera el pago; el comprador, una prueba. Verifica ruta, firma y recibos. La sombra busca tus manos.','एक पार्सल को अँधेरा गलियारा पार करना है। विक्रेता भुगतान चाहता है, खरीदार प्रमाण। रास्ता, हस्ताक्षर और दोनों रसीदें जाँचें। छाया अब आपके हाथ खोज रही है।','Un colis doit traverser un couloir sombre. Le vendeur attend son paiement, l’acheteur une preuve. Vérifiez le trajet, la signature et les reçus. L’ombre cherche vos mains.','Um pacote precisa atravessar um corredor escuro. O vendedor espera pagamento; o comprador, provas. Verifique o caminho, a assinatura e os recibos. A sombra procura suas mãos.'),
L('آشپزخانهٔ کودکی تو. پدر نانی را نصف می‌کند و سه پاکت بازنشده روی میز است. آب از زیر در می‌آید. لوله‌ها به خانه‌های دیگر می‌رسند. پیش از بستن شیر، مسیر هزینه را پیدا کن.','Your childhood kitchen. Father splits a loaf. Three unopened letters sit on the table. Water seeps under the door; pipes lead to other homes. Trace the cost before closing a valve.','童年的厨房。父亲掰开面包，桌上放着三封未拆的信。水从门缝渗入，管道通向其他家庭。关阀前先追踪代价。','مطبخ طفولتك. يقسم الأب رغيفاً وثلاث رسائل مغلقة على الطاولة. يتسرب الماء والأنابيب تصل إلى بيوت أخرى. تتبع التكلفة قبل إغلاق الصمام.','La cocina de tu infancia. Papá parte un pan. Tres cartas cerradas descansan en la mesa. Entra agua y las tuberías llegan a otras casas. Sigue el coste antes de cerrar una válvula.','बचपन की रसोई। पिता रोटी बाँट रहे हैं। मेज़ पर तीन बंद पत्र हैं। पानी भीतर आ रहा है, पाइप दूसरे घरों तक जाते हैं। वाल्व बंद करने से पहले लागत का रास्ता जानें।','La cuisine de votre enfance. Votre père partage du pain. Trois lettres sont fermées. L’eau entre et les tuyaux mènent à d’autres maisons. Suivez le coût avant de fermer une vanne.','A cozinha da sua infância. Seu pai divide um pão. Três cartas fechadas na mesa. A água entra e os canos levam a outras casas. Siga o custo antes de fechar uma válvula.'),
L('چند رایانهٔ معمولی. هیچ خزانه‌ای اینجا نیست. مانیتور می‌گوید: «ساتوشی؛ بازسازی ادبی». پیام را امضا کن، نسخه‌ها را وصل کن و ببین اگر نگهبان واحدی نباشد چه مسئولیتی بر عهدهٔ تو می‌ماند.','Ordinary computers. No vault. A screen reads “Satoshi: literary reconstruction.” Sign a message, connect the copies and discover what responsibility remains when there is no single keeper.','几台普通电脑，没有金库。屏幕写着：“中本聪：文学重建。”签署消息，连接副本，看看没有唯一保管人时，你承担什么责任。','حواسيب عادية، لا خزنة. الشاشة تقول «ساتوشي: إعادة بناء أدبية». وقّع رسالة ووصل النسخ واكتشف مسؤوليتك حين لا يوجد حارس واحد.','Ordenadores corrientes. Ninguna bóveda. «Satoshi: reconstrucción literaria». Firma un mensaje, conecta las copias y descubre tu responsabilidad cuando no hay un único guardián.','साधारण कंप्यूटर। कोई तिजोरी नहीं। स्क्रीन: «सातोशी: साहित्यिक पुनर्रचना।» संदेश पर हस्ताक्षर करें, प्रतियाँ जोड़ें और जानें कि अकेला संरक्षक न होने पर आपकी ज़िम्मेदारी क्या है।','Des ordinateurs ordinaires. Aucun coffre. «Satoshi : reconstitution littéraire.» Signez un message, reliez les copies et découvrez votre responsabilité sans gardien unique.','Computadores comuns. Nenhum cofre. “Satoshi: reconstrução literária.” Assine uma mensagem, conecte as cópias e descubra sua responsabilidade sem um guardião único.'),
L('دو جعبه زیر چراغ زرد. وقتی منو را باز می‌کنی، مینا ساکت می‌شود. وقتی می‌بندی، می‌پرسد: «سام؟ داشتی گوش می‌دادی؟» بلندگو را تعمیر کن و پیام امروز او را تا آخر بشنو.','Two boxes under a yellow light. Open a menu and Mina falls silent. Close it and she asks, “Sam? Were you listening?” Repair the speaker and hear today’s message to the end.','黄灯下有两个盒子。打开菜单，米娜便沉默；关上菜单，她问：“山姆，你在听吗？”修好扬声器，听完她今天的留言。','صندوقان تحت ضوء أصفر. تصمت مينا حين تفتح القائمة، وتقول حين تغلقها: «سام؟ هل كنت تسمعني؟» أصلح السماعة واسمع رسالتها حتى النهاية.','Dos cajas bajo una luz amarilla. Al abrir el menú, Mina calla. Al cerrarlo pregunta: «¿Sam? ¿Me escuchabas?». Repara el altavoz y escucha su mensaje completo.','पीली रोशनी के नीचे दो डिब्बे। मेनू खोलते ही मीना चुप हो जाती है। बंद करने पर पूछती है: «सैम, सुन रहे थे?» स्पीकर ठीक करें और उसका संदेश पूरा सुनें।','Deux boîtes sous une lumière jaune. Ouvrez le menu et Mina se tait. Fermez-le : «Sam ? Tu écoutais ?» Réparez le haut-parleur et écoutez son message jusqu’au bout.','Duas caixas sob luz amarela. Abra o menu e Mina se cala. Feche: “Sam? Você estava ouvindo?” Conserte o alto-falante e ouça a mensagem inteira.'),
L('آشپزخانهٔ ۲۸ ژانویهٔ ۲۰۲۱؛ این بار کف شیشه‌ای است. زیر پایت سفارش‌ها، وثیقه‌ها و گزارش‌ها جریان دارند. توضیح شرکت، بررسی مستقل و مسئولیت خودت را جداگانه ببین. سپس به سؤال مینا جواب بده.','January 28, 2021. This time the kitchen floor is glass. Orders, collateral and reports move below. Separate the company’s explanation, independent review and your own responsibility. Then answer Mina.','2021年1月28日。厨房地板变成玻璃，下面流动着订单、抵押物和报告。区分公司解释、独立审查与自己的责任，然后回答米娜。','28 يناير 2021. أرض المطبخ زجاجية الآن. تحتها طلبات وضمانات وتقارير. افصل تفسير الشركة عن المراجعة المستقلة ومسؤوليتك، ثم أجب مينا.','28 de enero de 2021. El suelo es de cristal. Debajo circulan órdenes, garantías e informes. Separa la explicación de la empresa, la revisión independiente y tu responsabilidad. Luego responde a Mina.','28 जनवरी 2021। अब रसोई का फ़र्श काँच का है। नीचे आदेश, ज़मानत और रिपोर्ट हैं। कंपनी की बात, स्वतंत्र समीक्षा और अपनी ज़िम्मेदारी अलग देखें। फिर मीना को जवाब दें।','28 janvier 2021. Le sol est de verre. Ordres, garanties et rapports circulent dessous. Distinguez explication de l’entreprise, examen indépendant et responsabilité personnelle. Puis répondez à Mina.','28 de janeiro de 2021. O chão é de vidro. Ordens, garantias e relatórios passam abaixo. Separe a explicação da empresa, a análise independente e sua responsabilidade. Depois responda a Mina.'),
L('هزاران نفر پشت پنجره‌ها منتظرند. صندوقدار مبلغ جبران را می‌گوید. کالای روی میز، خودِ حق خرید دیگران است. سه صاحب حق را پیدا کن، یا مستقیم نزد صندوقدار برو. راه خروج هنوز باز است.','Thousands wait behind windows. The cashier names your reimbursement. The product on the desk is other people’s right to buy. Find three rights holders, or speak directly to the cashier. The exit is still open.','数千人在窗后等待。收银员报出补偿金额。桌上的商品正是他人的购买权。寻找三位权利持有者，或直接与收银员交谈。出口仍然敞开。','آلاف ينتظرون خلف النوافذ. يذكر أمين الصندوق التعويض. البضاعة هي حق الآخرين في الشراء. ابحث عن ثلاثة أصحاب حقوق أو تحدث مباشرة معه. المخرج مفتوح.','Miles esperan tras las ventanas. El cajero ofrece tu reembolso. El producto es el derecho de otros a comprar. Busca a tres titulares o habla con el cajero. La salida sigue abierta.','हज़ारों लोग खिड़कियों के पीछे हैं। कैशियर भरपाई की रकम बताता है। मेज़ पर दूसरों का खरीदने का अधिकार बिक रहा है। तीन अधिकारधारियों को खोजें या कैशियर से बात करें। निकास खुला है।','Des milliers attendent derrière les fenêtres. Le caissier propose un remboursement. Le produit est le droit d’autrui d’acheter. Trouvez trois titulaires ou parlez au caissier. La sortie reste ouverte.','Milhares esperam nas janelas. O caixa oferece o reembolso. O produto é o direito dos outros de comprar. Encontre três titulares ou fale com o caixa. A saída continua aberta.')];

export const SOURCES=[
{id:'sec',title:'SEC · Market Structure Report, 2021',url:'https://www.sec.gov/files/staff-report-equity-options-market-struction-conditions-early-2021.pdf'},
{id:'met',title:'The Metropolitan Museum · The Origins of Writing',url:'https://www.metmuseum.org/essays/the-origins-of-writing'},
{id:'web',title:'Computer History Museum · Electronic Commerce',url:'https://www.computerhistory.org/revolution/story/392'},
{id:'net',title:'Fast Company · The Internet in 1994',url:'https://www.fastcompany.com/91140068/how-the-internet-went-mainstream-in-1994'},
{id:'fed',title:'Federal Reserve History · The Great Recession',url:'https://www.federalreservehistory.org/essays/great-recession-and-its-aftermath'},
{id:'btc',title:'Satoshi Nakamoto · Bitcoin P2P e-cash paper, 2008',url:'https://www.metzdowd.com/pipermail/cryptography/2008-October/014810.html'},
{id:'pizza',title:'BitcoinTalk · Pizza for bitcoins?, 2010',url:'https://bitcointalk.org/index.php?topic=137.0'},
{id:'rh',title:'Robinhood · An Update on Market Volatility, 2021',url:'https://robinhood.com/us/en/newsroom/an-update-on-market-volatility/'},
{id:'dospert',title:'Blais & Weber · Domain-Specific Risk-Taking, 2006',url:'https://sjdm.org/~baron/journal/06005/jdm06005.htm'}
];
const note=(body,source=null)=>({body,source});
export const RECORDS=[
[
note(L('مینا: «غذا کنار دره. وانت هشته. سیم‌های آبی رو دور نریز.»','Mina: “Food is by the door. The van comes at eight. Keep the blue cables.”','米娜：“饭在门口。货车八点到。别扔蓝色电线。”','مينا: «الطعام عند الباب. الشاحنة في الثامنة. احتفظ بالأسلاك الزرقاء».','Mina: «La comida está junto a la puerta. La furgoneta llega a las ocho. Guarda los cables azules».','मीना: «खाना दरवाज़े पर है। गाड़ी आठ बजे आएगी। नीले तार रखना।»','Mina : «Le repas est à la porte. Le camion arrive à huit heures. Garde les câbles bleus.»','Mina: “A comida está na porta. O caminhão chega às oito. Guarde os cabos azuis.”')),
note(L('پول مشترک، برای تعمیر سازها بود. سام پیش از معامله اجازه نگرفت. این گذشتهٔ شخصیت داستان است، نه انتخاب تو.','The shared money was for repairing instruments. Sam traded without asking. This is his backstory, not your choice.','共同存款原本用于修理乐器。山姆没有征求同意就交易了。这是角色的过去，不是你的选择。','المال المشترك لإصلاح الآلات. تداول سام دون سؤال. هذا ماضي الشخصية وليس اختيارك.','El dinero era para reparar instrumentos. Sam operó sin preguntar. Es su pasado, no tu decisión.','साझा धन वाद्य ठीक करने के लिए था। सैम ने बिना पूछे निवेश किया। यह पात्र का अतीत है, आपका चुनाव नहीं।','L’argent commun devait servir à réparer des instruments. Sam a négocié sans demander. C’est son passé, pas votre choix.','O dinheiro era para consertar instrumentos. Sam negociou sem perguntar. É o passado dele, não sua escolha.')),
note(L('محدودیت خرید، مالکیت سهام قبلی را حذف نمی‌کرد. خرید، فروش و نگهداری سه عمل متفاوت‌اند.','Purchase restrictions did not erase existing share ownership. Buying, selling and holding are different actions.','购买限制并不抹去已有股份的所有权。买入、卖出与持有是不同的行为。','قيود الشراء لم تمح ملكية الأسهم القائمة. الشراء والبيع والاحتفاظ أفعال مختلفة.','Las restricciones de compra no borraban la propiedad de acciones. Comprar, vender y mantener son acciones distintas.','खरीद पर रोक से पहले के शेयरों का स्वामित्व नहीं मिटा। खरीदना, बेचना और रखना अलग क्रियाएँ हैं।','Les restrictions d’achat n’effaçaient pas les actions détenues. Acheter, vendre et conserver sont des actes distincts.','Restrições de compra não apagavam ações já possuídas. Comprar, vender e manter são ações diferentes.'),'sec'),
note(L('پشت یک عکس نوشته: «با هم حرف بزنیم.» تاریخ ندارد.','On the back of a photograph: “Let’s talk together.” No date.','照片背面写着：“我们谈谈吧。”没有日期。','خلف صورة: «لنتحدث معاً». بلا تاريخ.','Detrás de una foto: «Hablemos juntos». Sin fecha.','तस्वीर के पीछे: «आओ बात करें।» तारीख नहीं।','Au dos d’une photo : «Parlons ensemble.» Aucune date.','Atrás de uma foto: “Vamos conversar.” Sem data.'))
],
[
note(L('ته ظرف دو قسمت دارد: خوراک امروز و بذر فردا. از دور هر دو یک کالا بودند.','The bowl has two parts: food for today and seeds for tomorrow. From afar they looked like one commodity.','碗分两半：今天的食物与明天的种子。远看却像同一种商品。','الوعاء قسمان: طعام اليوم وبذور الغد. من بعيد بدوا سلعة واحدة.','El cuenco tiene comida para hoy y semillas para mañana. De lejos parecían una sola mercancía.','कटोरे में आज का भोजन और कल के बीज हैं। दूर से दोनों एक वस्तु थे।','Le bol contient nourriture du jour et graines pour demain. De loin, une seule marchandise.','A tigela tem comida para hoje e sementes para amanhã. De longe, pareciam uma mercadoria só.')),
note(L('تیغه ترک دارد. دیدنِ عیب، قول فردا را مطمئن نمی‌کند؛ فقط نادانی امروز را کمتر می‌کند.','The blade is cracked. Seeing its flaw cannot guarantee tomorrow; it only reduces today’s uncertainty.','刀刃有裂痕。看到缺陷不能保证明天，只能减少今天的未知。','الشفرة مشقوقة. معرفة العيب لا تضمن الغد، بل تقلل جهل اليوم.','La hoja está agrietada. Ver el defecto no garantiza mañana; reduce la incertidumbre de hoy.','औज़ार में दरार है। दोष जानने से कल की गारंटी नहीं, आज की अनिश्चितता कम होती है।','La lame est fissurée. Voir le défaut ne garantit pas demain ; cela réduit l’incertitude présente.','A lâmina está rachada. Ver o defeito não garante amanhã; reduz a incerteza de hoje.')),
note(L('لوح‌های باستانی، ثبت فعالیت اقتصادی را نشان می‌دهند؛ هویت نخستین خریدار بشر را معلوم نمی‌کنند.','Ancient tablets record economic activity; they do not identify humanity’s first buyer.','古代泥板记录经济活动，却无法确认人类第一位买家。','الألواح القديمة تسجل نشاطاً اقتصادياً، ولا تحدد أول مشترٍ بشري.','Las tablillas antiguas registran actividad económica, no identifican al primer comprador humano.','प्राचीन तख्तियाँ आर्थिक गतिविधियाँ बताती हैं, पहले मानव खरीदार की पहचान नहीं।','Les tablettes anciennes attestent des activités économiques, sans identifier le premier acheteur humain.','Tabuletas antigas registram atividade econômica, não identificam o primeiro comprador humano.'),'met'),
note(L('دو اثر انگشت روی گل هست. یکی از طرف‌ها نمی‌تواند به‌جای هر دو رضایت بدهد.','Two fingerprints mark the clay. One party cannot consent for both.','泥上有两个指印。一方不能替双方同意。','بصمتان على الطين. لا يوافق طرف نيابة عن كليهما.','Dos huellas en la arcilla. Nadie puede consentir por ambos.','मिट्टी पर दो उँगलियों के निशान। एक पक्ष दोनों की सहमति नहीं दे सकता।','Deux empreintes dans l’argile. Une partie ne peut consentir pour les deux.','Duas impressões na argila. Uma parte não pode consentir pelas duas.'))
],
[
note(L('تجارت الکترونیک پیش از وب هم وجود داشت. «اولین» به تعریف پرسش بستگی دارد.','Electronic commerce existed before the Web. “First” depends on what you are counting.','电子商务早于万维网。“第一”取决于定义。','وُجدت التجارة الإلكترونية قبل الويب. «الأول» يتوقف على التعريف.','El comercio electrónico precede a la Web. «Primero» depende de qué se cuente.','इलेक्ट्रॉनिक व्यापार वेब से पहले था। «पहला» परिभाषा पर निर्भर है।','Le commerce électronique précède le Web. «Premier» dépend de ce que l’on compte.','O comércio eletrônico veio antes da Web. “Primeiro” depende da definição.'),'web'),
note(L('۱۱ اوت ۱۹۹۴: خرید سی‌دی استینگ از NetMarket؛ یکی از نخستین خریدهای امن مشهور وب، با ادعاهای رقیب دربارهٔ تقدم.','August 11, 1994: a Sting CD bought on NetMarket, an early famous secure Web purchase with competing priority claims.','1994年8月11日：在 NetMarket 购买 Sting 的唱片。这是著名的早期安全网络购物，“首次”仍有争议。','11 أغسطس 1994: شراء قرص ستينغ من NetMarket، من أشهر المشتريات الآمنة المبكرة مع خلاف على الأسبقية.','11 de agosto de 1994: un CD de Sting en NetMarket, compra segura temprana y famosa, con disputas sobre la primacía.','11 अगस्त 1994: NetMarket पर Sting की सीडी, शुरुआती प्रसिद्ध सुरक्षित वेब खरीद; पहले होने के दावे विवादित हैं।','11 août 1994 : un CD de Sting sur NetMarket, achat sécurisé précoce célèbre dont la priorité reste disputée.','11 de agosto de 1994: um CD de Sting no NetMarket, compra segura pioneira famosa, com prioridade disputada.'),'net'),
note(L('الیاس: «اگر یک روز گفتند تو قبول کرده‌ای، نسخهٔ خودت را هم ببین.»','Elias: “If they ever say you agreed, check your own copy too.”','伊莱亚斯：“如果有人说你同意过，也看看自己的副本。”','إلياس: «إن قالوا يوماً إنك وافقت، افحص نسختك أيضاً».','Elías: «Si dicen que aceptaste, revisa también tu copia».','इलियास: «यदि वे कहें कि तुम सहमत थे, अपनी प्रति भी देखना।»','Élias : «S’ils disent que tu as accepté, regarde aussi ta copie.»','Elias: “Se disserem que você concordou, verifique sua própria cópia.”')),
note(L('واسطه مسیر را کوتاه می‌کند. اختیار حل اختلاف هم به دست او می‌رسد.','The intermediary shortens the route and gains authority over disputes.','中间人缩短路线，也获得处理争议的权力。','الوسيط يقصّر الطريق ويكتسب سلطة الفصل في النزاع.','El intermediario acorta el trayecto y obtiene autoridad sobre las disputas.','मध्यस्थ रास्ता छोटा करता है और विवाद निपटाने का अधिकार पाता है।','L’intermédiaire raccourcit le trajet et obtient le pouvoir d’arbitrer.','O intermediário encurta o caminho e ganha autoridade sobre disputas.'))
],
[
note(L('پدر دوباره همان جمله را می‌گوید. این تصویر فقط خاطرهٔ توست؛ پاسخ تازه‌ای از او ندارد.','Father repeats the same line. This image is only your memory; it has no new answer from him.','父亲重复着同一句话。这只是你的记忆，无法给出他的新回答。','يكرر الأب الجملة نفسها. الصورة ذاكرتك فقط، لا تحمل جواباً جديداً منه.','Papá repite la misma frase. Es tu recuerdo; no tiene una respuesta nueva de él.','पिता वही वाक्य दोहराते हैं। यह आपकी याद है; इसमें उनका नया उत्तर नहीं।','Votre père répète la même phrase. Ce souvenir n’a pas de réponse nouvelle à donner.','Seu pai repete a frase. É apenas sua memória; não tem uma resposta nova dele.')),
note(L('بحران مالی ۲۰۰۷ تا ۲۰۰۹ چندعلتی بود. این خانه و خانواده بازسازی داستانی‌اند.','The 2007–2009 financial crisis had multiple causes. This home and family are fictional.','2007至2009年金融危机有多重原因。这间房屋和家庭是虚构的。','للأزمة المالية 2007–2009 أسباب متعددة. هذا البيت والعائلة خياليان.','La crisis de 2007–2009 tuvo varias causas. Esta casa y familia son ficticias.','2007–2009 के वित्तीय संकट के अनेक कारण थे। यह घर और परिवार काल्पनिक हैं।','La crise de 2007–2009 avait plusieurs causes. Cette maison et cette famille sont fictives.','A crise de 2007–2009 teve várias causas. Esta casa e família são fictícias.'),'fed'),
note(L('شیر سمت راست، آب را حذف نمی‌کند. آن را به خانه‌ای می‌فرستد که هنوز ندیده‌ای.','The right-hand valve does not remove water. It sends it to a house you have not seen.','右边的阀门不会消灭水，而是将水送往你没见过的房子。','الصمام الأيمن لا يمحو الماء، بل يرسله إلى بيت لم تره.','La válvula derecha no elimina el agua. La envía a una casa que no has visto.','दायाँ वाल्व पानी मिटाता नहीं, उसे अनदेखे घर भेजता है।','La vanne de droite n’efface pas l’eau. Elle l’envoie vers une maison inconnue.','A válvula direita não elimina a água. Envia para uma casa que você não viu.')),
note(L('پشت پاکت پدر: «با هم حرف بزنیم.» پاکت هرگز باز نشده بود.','On Father’s envelope: “Let’s talk together.” It was never opened.','父亲的信封背面：“我们谈谈吧。”信从未拆开。','خلف ظرف الأب: «لنتحدث معاً». لم يُفتح قط.','En el sobre de papá: «Hablemos juntos». Nunca se abrió.','पिता के लिफ़ाफ़े पर: «आओ बात करें।» वह कभी खुला नहीं।','Sur l’enveloppe de votre père : «Parlons ensemble.» Elle n’a jamais été ouverte.','No envelope do pai: “Vamos conversar.” Nunca foi aberto.'))
],
[
note(L('۳۱ اکتبر ۲۰۰۸: معرفی مقالهٔ بیت‌کوین در فهرست ایمیلی رمزنگاری. گفت‌وگوهای این اتاق، نقل‌قول تاریخی نیستند.','October 31, 2008: the Bitcoin paper is announced on the cryptography mailing list. This room’s dialogue is fictional.','2008年10月31日：比特币论文在密码学邮件列表公布。本房间的对话是虚构的。','31 أكتوبر 2008: الإعلان عن ورقة بيتكوين في قائمة التشفير. حوار هذه الغرفة خيالي.','31 de octubre de 2008: anuncio del artículo de Bitcoin en la lista de criptografía. El diálogo de esta sala es ficticio.','31 अक्टूबर 2008: क्रिप्टोग्राफ़ी सूची में Bitcoin लेख की घोषणा। इस कमरे के संवाद काल्पनिक हैं।','31 octobre 2008 : annonce de l’article Bitcoin sur la liste de cryptographie. Les dialogues de cette pièce sont fictifs.','31 de outubro de 2008: anúncio do artigo Bitcoin na lista de criptografia. O diálogo desta sala é fictício.'),'btc'),
note(L('سام: «خودتی؟» پاسخ: «این اتاق نمی‌داند صورتم چه شکلی است.»','Sam: “Is it you?” Reply: “This room does not know what my face looks like.”','山姆：“是你吗？”回答：“这个房间不知道我长什么样。”','سام: «هل أنت هو؟» الرد: «لا تعرف هذه الغرفة شكل وجهي».','Sam: «¿Eres tú?». Respuesta: «Esta habitación no sabe cómo es mi cara».','सैम: «क्या तुम हो?» उत्तर: «यह कमरा मेरा चेहरा नहीं जानता।»','Sam : «C’est toi ?» Réponse : «Cette pièce ne connaît pas mon visage.»','Sam: “É você?” Resposta: “Esta sala não conhece meu rosto.”')),
note(L('یک نسخهٔ مستقل، با خاموش‌شدن رایانهٔ دیگر از بین نمی‌رود. نگهداری و دسترسی همچنان مسئولیت می‌خواهند.','An independent copy survives another computer shutting down. Storage and access still need care.','独立副本不会随另一台电脑关机而消失，但保存和访问仍需负责。','تبقى النسخة المستقلة عند توقف حاسوب آخر. التخزين والوصول يحتاجان عناية.','Una copia independiente sobrevive al apagado de otro equipo. Guardarla y acceder a ella sigue exigiendo cuidado.','दूसरा कंप्यूटर बंद होने पर स्वतंत्र प्रति रहती है। संग्रह और पहुँच की देखभाल फिर भी चाहिए।','Une copie indépendante survit à l’arrêt d’un autre ordinateur. Stockage et accès exigent toujours du soin.','Uma cópia independente sobrevive ao desligamento de outro computador. Guardar e acessar ainda exige cuidado.')),
note(L('روی دیوار قیمت آیندهٔ هیچ‌چیز نوشته نشده. امضا، تضمین سود نیست.','No future prices are written on the wall. A signature is not a promise of profit.','墙上没有未来价格。签名不等于收益保证。','لا أسعار مستقبلية على الجدار. التوقيع ليس ضمان ربح.','No hay precios futuros en la pared. Una firma no promete beneficios.','दीवार पर भविष्य की कीमतें नहीं। हस्ताक्षर लाभ की गारंटी नहीं।','Aucun prix futur sur le mur. Une signature ne promet pas de profit.','Não há preços futuros na parede. Assinatura não promete lucro.'))
],
[
note(L('۲۲ مه ۲۰۱۰: اعلام انجام مبادلهٔ دو پیتزا در برابر ۱۰٬۰۰۰ بیت‌کوین. آینده برای خریدار معلوم نبود.','May 22, 2010: completion of a trade of 10,000 bitcoins for two pizzas was reported. The buyer did not know the future.','2010年5月22日：用一万枚比特币购买两张披萨的交易被确认完成。买家并不知道未来。','22 مايو 2010: إعلان إتمام مبادلة عشرة آلاف بيتكوين ببيتزتين. لم يعرف المشتري المستقبل.','22 de mayo de 2010: se comunicó el intercambio de 10.000 bitcoins por dos pizzas. El comprador no conocía el futuro.','22 मई 2010: 10,000 बिटकॉइन में दो पिज़्ज़ा का सौदा पूरा होने की सूचना। खरीदार भविष्य नहीं जानता था।','22 mai 2010 : confirmation d’un échange de 10 000 bitcoins contre deux pizzas. L’acheteur ignorait l’avenir.','22 de maio de 2010: confirmação da troca de 10.000 bitcoins por duas pizzas. O comprador não conhecia o futuro.'),'pizza'),
note(L('خاطرهٔ خانوادهٔ سام: «وقتی کارگاهت بزرگ شد، باز هم بذاری من توش کار کنم؟»','A memory from Sam’s family: “When your workshop gets bigger, will you still let me work there?”','山姆家的记忆：“等你的工作室变大了，还会让我在那里工作吗？”','ذكرى عائلة سام: «حين تكبر ورشتك، هل تسمح لي بالعمل فيها؟»','Un recuerdo de Sam: «Cuando tu taller sea grande, ¿me dejarás seguir trabajando allí?».','सैम की पारिवारिक याद: «जब कार्यशाला बड़ी होगी, क्या मुझे वहाँ काम करने दोगे?»','Un souvenir de Sam : «Quand ton atelier sera plus grand, tu me laisseras encore y travailler ?»','Uma memória de Sam: “Quando sua oficina crescer, ainda vai me deixar trabalhar lá?”')),
note(L('پیام امروز مینا آدرس یک کارگاه تازه است. او برای شروع دوباره منتظر تصمیم سام نمانده.','Today’s message is Mina’s new workshop address. She did not wait for Sam to decide before starting over.','今天的留言是米娜新工作室的地址。她没有等山姆做决定才重新开始。','رسالة اليوم عنوان ورشة مينا الجديدة. لم تنتظر قرار سام لتبدأ من جديد.','El mensaje trae la dirección del nuevo taller de Mina. No esperó a Sam para empezar otra vez.','आज का संदेश मीना की नई कार्यशाला का पता है। उसने फिर शुरू करने के लिए सैम का इंतज़ार नहीं किया।','Le message donne l’adresse du nouvel atelier de Mina. Elle n’a pas attendu Sam pour recommencer.','A mensagem tem o endereço da nova oficina de Mina. Ela não esperou Sam para recomeçar.')),
note(L('غذا امروز کاربرد دارد. نگهداری هم ممکن است ارزش داشته باشد. یک عدد، همهٔ زندگی را توضیح نمی‌دهد.','Food has a use today. Saving may also have value. One number cannot explain a whole life.','食物今天就有用，储存也可能有价值。一个数字无法解释整个人生。','للطعام فائدة اليوم، وللادخار قيمة محتملة. رقم واحد لا يفسر حياة كاملة.','La comida sirve hoy. Ahorrar también puede valer. Un número no explica toda una vida.','भोजन आज काम आता है। बचत का भी मूल्य हो सकता है। एक संख्या पूरी ज़िंदगी नहीं समझाती।','La nourriture sert aujourd’hui. Épargner peut aussi avoir une valeur. Un chiffre n’explique pas une vie.','Comida serve hoje. Guardar também pode valer. Um número não explica uma vida inteira.'))
],
[
note(L('شرکت به الزامات مالی و سپردهٔ تسویه استناد کرد. این توضیح یکی از طرف‌های واقعه است.','The company cited financial and clearing deposit requirements. This is one participant’s explanation.','公司提到资金和清算保证金要求。这是事件一方的解释。','استندت الشركة إلى متطلبات مالية وودائع تسوية. هذا تفسير أحد الأطراف.','La empresa citó requisitos financieros y depósitos de compensación. Es la explicación de una de las partes.','कंपनी ने वित्तीय और निपटान जमा की आवश्यकताएँ बताईं। यह एक पक्ष का स्पष्टीकरण है।','L’entreprise a invoqué des exigences financières et des dépôts de compensation. C’est l’explication d’une partie.','A empresa citou exigências financeiras e depósitos de compensação. É a explicação de uma das partes.'),'rh'),
note(L('گزارش SEC سازوکار بازار و محدودیت‌ها را بررسی می‌کند. از آن نمی‌توان سود قطعی سفارش انجام‌نشدهٔ سام را نتیجه گرفت.','The SEC report examines market mechanics and restrictions. It cannot establish guaranteed profit for Sam’s unfilled order.','SEC 报告分析市场机制和限制，但不能证明山姆未成交订单必然获利。','يفحص تقرير SEC آليات السوق والقيود، ولا يثبت ربحاً مضموناً لأمر سام غير المنفذ.','El informe SEC examina el mercado y las restricciones. No demuestra beneficios seguros para la orden de Sam.','SEC रिपोर्ट बाज़ार और पाबंदियाँ जाँचती है। इससे सैम के अधूरे आदेश का निश्चित लाभ सिद्ध नहीं होता।','Le rapport SEC examine le marché et les restrictions. Il ne garantit aucun profit pour l’ordre inexécuté de Sam.','O relatório SEC examina o mercado e as restrições. Não garante lucro para a ordem não executada de Sam.'),'sec'),
note(L('مینا هنوز همان سؤال را می‌پرسد: «پول من هم توشه؟» گوشی را می‌توانی پایین بیاوری.','Mina still asks the same question: “Is my money in there too?” You can lower the phone.','米娜还是那个问题：“我的钱也在里面吗？”你可以放下手机。','مينا تسأل السؤال نفسه: «هل مالي فيها أيضاً؟» يمكنك خفض الهاتف.','Mina repite: «¿Mi dinero también está ahí?». Puedes bajar el teléfono.','मीना का वही सवाल: «क्या मेरा पैसा भी उसमें है?» फ़ोन नीचे रख सकते हैं।','Mina répète : «Mon argent y est aussi ?» Vous pouvez baisser le téléphone.','Mina repete: “Meu dinheiro está aí também?” Você pode baixar o telefone.')),
note(L('پذیرفتن مسئولیت خودت، نیازمند توجیه رفتار شرکت نیست. دو مسئولیت می‌توانند هم‌زمان وجود داشته باشند.','Owning your responsibility does not require excusing the company. Two responsibilities can coexist.','承担自己的责任不等于替公司辩解。两种责任可以同时存在。','قبول مسؤوليتك لا يتطلب تبرير الشركة. يمكن لمسؤوليتين أن تتزامنا.','Asumir tu responsabilidad no exige justificar a la empresa. Ambas pueden coexistir.','अपनी ज़िम्मेदारी मानने के लिए कंपनी का बचाव ज़रूरी नहीं। दोनों ज़िम्मेदारियाँ साथ हो सकती हैं।','Assumer votre responsabilité n’exige pas d’excuser l’entreprise. Deux responsabilités peuvent coexister.','Assumir sua responsabilidade não exige desculpar a empresa. As duas podem coexistir.'))
],
[
note(L('شرکت‌کنندگان این تالار حاضرند؛ بازسازی تاریخی نیستند. هیچ‌کس به‌جای آن‌ها امضا نمی‌کند.','The people in this hall are present participants, not historical reconstructions. Nobody signs on their behalf.','大厅里的人是真实参与者，不是历史重建。没有人能代替他们签字。','أهل هذه القاعة مشاركون حاضرون، لا صور تاريخية. لا يوقع أحد عنهم.','Las personas de esta sala participan ahora, no son reconstrucciones. Nadie firma por ellas.','इस हॉल के लोग वर्तमान प्रतिभागी हैं, ऐतिहासिक छवियाँ नहीं। कोई उनके बदले हस्ताक्षर नहीं करता।','Les personnes de cette salle participent réellement, ce ne sont pas des reconstitutions. Nul ne signe à leur place.','As pessoas deste salão são participantes presentes, não reconstruções. Ninguém assina por elas.')),
note(L('صندوقدار: «لازم نیست تو را کامل بشناسم. برای پیشنهاد بعدی همین‌قدر کافی است.»','Cashier: “I do not need to know you completely. This is enough for the next offer.”','收银员：“不必完全了解你。这些足够提出下一份报价。”','أمين الصندوق: «لا أحتاج إلى معرفتك تماماً. هذا يكفي للعرض التالي».','Cajero: «No necesito conocerte del todo. Basta para la próxima oferta».','कैशियर: «तुम्हें पूरी तरह जानना ज़रूरी नहीं। अगले प्रस्ताव के लिए इतना काफ़ी है।»','Le caissier : «Je n’ai pas besoin de tout savoir de vous. Cela suffit à la prochaine offre.»','Caixa: “Não preciso conhecer você por completo. Isso basta para a próxima oferta.”')),
note(L('نسخه‌های مستقل، حق بررسی را نگه می‌دارند. نابودکردن دفتر مرکزی ممکن است مدرک یک طلب واقعی را هم بسوزاند.','Independent copies preserve the right to verify. Destroying the central ledger may erase evidence of a real claim.','独立副本保留核验权。摧毁中央账本可能同时抹去真实债权的证据。','تحفظ النسخ المستقلة حق التحقق. تدمير السجل المركزي قد يمحو دليل مطالبة حقيقية.','Las copias independientes conservan la verificación. Destruir el registro central puede borrar pruebas de una deuda real.','स्वतंत्र प्रतियाँ जाँच का अधिकार रखती हैं। केंद्रीय बही नष्ट करने से वास्तविक दावे का प्रमाण मिट सकता है।','Les copies indépendantes préservent le droit de vérifier. Détruire le registre peut effacer une créance réelle.','Cópias independentes preservam a verificação. Destruir o registro pode apagar provas de uma dívida real.')),
note(L('کنار خروج، همان کیسهٔ غذاست. راه رفتن همیشه باز بوده؛ هزینه‌اش را هم از اول می‌دانستی.','The same bag of food waits by the exit. Leaving was always possible; its cost was always visible.','出口旁还是那袋饭。离开一直是可能的，代价也一直清楚。','كيس الطعام نفسه عند المخرج. كان الرحيل ممكناً دائماً، وتكلفته واضحة.','La misma bolsa espera junto a la salida. Irte siempre fue posible y su coste era visible.','निकास पर वही खाने का थैला है। जाना हमेशा संभव था, और लागत साफ़ थी।','Le même repas attend près de la sortie. Partir était toujours possible et le coût était connu.','A mesma sacola espera na saída. Partir sempre foi possível e o custo estava claro.'))
]
];

const choice=(text,tags)=>({text,tags});
export const CHOICES=[
[
choice(L('به مینا بگو پول مشترک در معامله بود؛ گفت‌وگوی سخت را عقب نینداز.','Tell Mina the shared money was in the trade. Do not delay the difficult conversation.','告诉米娜共同的钱用于交易，不再拖延困难的对话。','أخبر مينا أن المال المشترك كان في الصفقة. لا تؤجل الحديث الصعب.','Dile a Mina que el dinero común estaba invertido. No retrases la conversación difícil.','मीना को साझा पैसे के सौदे में होने का सच बताएँ। कठिन बात न टालें।','Dites à Mina que l’argent commun était engagé. Ne retardez pas la conversation difficile.','Diga a Mina que o dinheiro comum estava na operação. Não adie a conversa difícil.'),['accountable']),
choice(L('اول دنبال جبران بگرد؛ مینا فعلاً پاسخ روشنی نمی‌گیرد.','Seek repayment first. Mina will not get a clear answer yet.','先寻求赔偿，米娜暂时得不到明确答复。','ابحث عن التعويض أولاً. لن تحصل مينا على جواب واضح الآن.','Busca recuperar el dinero primero. Mina aún no tendrá respuesta clara.','पहले भरपाई खोजें। मीना को अभी स्पष्ट उत्तर नहीं मिलेगा।','Cherchez d’abord un remboursement. Mina n’aura pas encore de réponse claire.','Busque o reembolso primeiro. Mina ainda não terá resposta clara.'),['recovery']),
choice(L('از او زمان بخواه؛ قول جبران نده و تصمیم تازه‌ای برای پولش نگیر.','Ask for time. Promise no repayment and make no new decision with her money.','向她请求时间，不承诺补偿，也不再替她的钱作决定。','اطلب وقتاً. لا تعد بالتعويض ولا تتخذ قراراً جديداً بمالها.','Pide tiempo. No prometas recuperarlo ni tomes otra decisión con su dinero.','समय माँगें। भरपाई का वादा या उसके पैसे पर नया निर्णय न करें।','Demandez du temps, sans promettre un remboursement ni décider à nouveau pour son argent.','Peça tempo. Não prometa reembolso nem decida novamente pelo dinheiro dela.'),['consent'])
],
[
choice(L('نسخهٔ هر دو نفر را حفظ کن؛ اعتبار اضافه را از دست می‌دهی.','Keep both people’s copies. Forgo the extra credit.','保留双方副本，放弃额外额度。','احفظ نسختي الطرفين، وتنازل عن الرصيد الإضافي.','Conserva ambas copias. Renuncia al crédito extra.','दोनों की प्रतियाँ रखें। अतिरिक्त क्रेडिट छोड़ें।','Conservez les deux copies et renoncez au crédit supplémentaire.','Guarde as duas cópias e abra mão do crédito extra.'),['evidence','consent']),
choice(L('نگهداری رسید را به صندوق بسپار؛ اعتبار می‌گیری اما نسخهٔ مستقل نداری.','Let the cashier keep the receipt. Gain credit but hold no independent copy.','将收据交给收银员保管，获得额度，但失去独立副本。','سلّم الإيصال للصندوق. تحصل على رصيد دون نسخة مستقلة.','Deja el recibo al cajero. Obtén crédito, sin copia independiente.','कैशियर को रसीद रखने दें। क्रेडिट मिलेगा, स्वतंत्र प्रति नहीं।','Confiez le reçu au caissier. Recevez un crédit, sans copie indépendante.','Entregue o recibo ao caixa. Ganhe crédito, sem cópia independente.'),['delegate']),
choice(L('کار فردایت را قول بده تا بذرها برای هر دو باقی بمانند؛ آینده تضمین نیست.','Promise tomorrow’s labor so both can keep seeds. The future is uncertain.','承诺明天的劳动，让双方保留种子。未来仍不确定。','عِد بعمل الغد ليحتفظ الطرفان بالبذور. المستقبل غير مضمون.','Promete tu trabajo de mañana para que ambos conserven semillas. El futuro es incierto.','दोनों के बीज बचाने के लिए कल का श्रम दें। भविष्य निश्चित नहीं।','Promettez votre travail de demain pour garder les graines des deux parties. L’avenir reste incertain.','Prometa seu trabalho de amanhã para ambos guardarem sementes. O futuro é incerto.'),['risk','consent'])
],
[
choice(L('تحویل مستقیم با دو رسید؛ زمان بیشتر، امکان بررسی مستقل.','Direct delivery with two receipts: more work, independent verification.','直接交付并保留两份收据：更费力，但可独立验证。','تسليم مباشر بإيصالين: جهد أكبر وتحقق مستقل.','Entrega directa con dos recibos: más trabajo y verificación independiente.','दो रसीदों के साथ सीधी डिलीवरी: अधिक काम, स्वतंत्र जाँच।','Livraison directe avec deux reçus : plus d’effort, vérification indépendante.','Entrega direta com dois recibos: mais trabalho, verificação independente.'),['evidence']),
choice(L('واسطه تحویل را انجام دهد؛ حل اختلاف هم به او سپرده می‌شود.','Use the intermediary for delivery and give them authority to settle disputes.','使用中间人交付，并将争议裁决权交给对方。','استخدم الوسيط للتسليم وامنحه سلطة فض النزاع.','Usa al intermediario para entregar y resolver disputas.','डिलीवरी और विवाद निपटान का अधिकार मध्यस्थ को दें।','Confiez livraison et arbitrage des litiges à l’intermédiaire.','Use o intermediário para entregar e resolver disputas.'),['delegate']),
choice(L('تا دریافت مدرک بیشتر صبر کن؛ ممکن است این معامله را از دست بدهی.','Wait for more evidence. This deal may be lost.','等待更多证据，可能因此错过交易。','انتظر دليلاً إضافياً. قد تضيع الصفقة.','Espera más pruebas. Podrías perder el trato.','और प्रमाण की प्रतीक्षा करें। सौदा हाथ से जा सकता है।','Attendez plus de preuves, au risque de perdre cette affaire.','Espere mais provas. Você pode perder o negócio.'),['evidence','patience'])
],
[
choice(L('هزینه را از سهم خودت بده؛ دارایی‌ات کمتر می‌شود و خطر منتقل نمی‌شود.','Pay from your own share. Keep less, without transferring the risk.','用自己的份额支付，留下更少，但不转移风险。','ادفع من حصتك. يبقى لك أقل دون نقل الخطر.','Paga con tu parte. Te queda menos, sin transferir riesgo.','अपने हिस्से से चुकाएँ। कम बचेगा, लेकिन जोखिम नहीं जाएगा।','Payez sur votre part. Il vous reste moins, sans transférer le risque.','Pague com sua parte. Sobra menos, sem transferir o risco.'),['selfcost']),
choice(L('شیر را به خانهٔ بعدی باز کن؛ اتاق تو خشک می‌شود و هزینه به دیگری می‌رسد.','Open the valve into the next house. Your room dries; someone else bears the cost.','将阀门开向邻家：你的房间干了，代价由别人承担。','افتح الصمام إلى البيت التالي. تجف غرفتك ويتحمل الآخر التكلفة.','Abre la válvula hacia otra casa. Tu cuarto se seca; otro paga el coste.','वाल्व अगले घर की ओर खोलें। आपका कमरा सूखेगा, कीमत दूसरा देगा।','Ouvrez vers la maison voisine. Votre pièce sèche ; autrui supporte le coût.','Abra a válvula para a casa vizinha. Seu quarto seca; outra pessoa paga.'),['transfer']),
choice(L('با همسایه دربارهٔ تقسیم هزینه توافق کن؛ اختیار ردکردن را برایش نگه دار.','Negotiate sharing the cost. Preserve the neighbor’s right to refuse.','协商分担费用，并保留邻居拒绝的权利。','تفاوض لتقاسم التكلفة واحفظ حق الجار في الرفض.','Negocia compartir el coste y respeta el derecho del vecino a negarse.','लागत बाँटने पर बात करें। पड़ोसी का मना करने का अधिकार रखें।','Négociez le partage du coût en préservant le droit du voisin de refuser.','Negocie dividir o custo e preserve o direito do vizinho de recusar.'),['consent','selfcost'])
],
[
choice(L('کلید را خودت نگه دار؛ مسئولیت نگهداری و بازیابی هم با توست.','Keep the key yourself, along with responsibility for its storage and recovery.','自己保管密钥，同时承担存储与恢复的责任。','احفظ المفتاح بنفسك، مع مسؤولية التخزين والاستعادة.','Guarda la clave y asume conservarla y recuperarla.','कुंजी खुद रखें; संग्रह और पुनर्प्राप्ति की ज़िम्मेदारी भी आपकी।','Gardez la clé et assumez sa conservation et sa récupération.','Guarde a chave e assuma sua conservação e recuperação.'),['autonomy']),
choice(L('کلید را به نگهبان بسپار؛ راحتی بیشتر و وابستگی به دسترسی او.','Entrust the key to a keeper: more convenience, dependence on their access.','把密钥交给保管人：更方便，但依赖对方开放访问。','سلّم المفتاح لحارس: راحة أكثر واعتماد على وصوله.','Confía la clave a un guardián: comodidad y dependencia de su acceso.','संरक्षक को कुंजी दें: सुविधा अधिक, पहुँच पर निर्भरता।','Confiez la clé à un gardien : plus pratique, mais accès dépendant de lui.','Confie a chave a um guardião: mais conveniência e dependência do acesso dele.'),['delegate']),
choice(L('چند امضا لازم باشد؛ قدرت تقسیم می‌شود و هماهنگی دشوارتر است.','Require several signatures: shared authority, harder coordination.','需要多个签名：权力分散，协调更难。','اشترط عدة توقيعات: سلطة موزعة وتنسيق أصعب.','Exige varias firmas: autoridad compartida, coordinación más difícil.','कई हस्ताक्षर रखें: अधिकार बँटेंगे, तालमेल कठिन होगा।','Exigez plusieurs signatures : pouvoir partagé, coordination plus difficile.','Exija várias assinaturas: autoridade compartilhada, coordenação mais difícil.'),['evidence','consent'])
],
[
choice(L('بخور و به راه ادامه بده؛ توان امروزت برمی‌گردد.','Eat and continue. Restore your energy for today.','吃下去再继续，恢复今天的体力。','كُل وتابع. تستعيد طاقة اليوم.','Come y sigue. Recupera energía para hoy.','खाएँ और चलें। आज की ऊर्जा लौटेगी।','Mangez et continuez. Retrouvez votre énergie du jour.','Coma e continue. Recupere energia para hoje.'),['present']),
choice(L('با مینا تقسیم کن و به پیامش گوش بده؛ سهم کمتری برای تو می‌ماند.','Share with Mina and listen to her message. Keep a smaller portion.','与米娜分享并听她的留言，自己的份量更少。','شارك مينا واستمع لرسالتها. يبقى لك نصيب أصغر.','Comparte con Mina y escucha su mensaje. Te queda menos.','मीना के साथ बाँटें और उसका संदेश सुनें। आपका हिस्सा कम होगा।','Partagez avec Mina et écoutez son message. Gardez une part plus petite.','Divida com Mina e ouça a mensagem. Sua parte fica menor.'),['consent','selfcost']),
choice(L('برای بعد نگه دار؛ فایدهٔ امروز را به امکان فردا ترجیح نمی‌دهی.','Save it for later. Give up today’s benefit to preserve tomorrow’s option.','留到以后，放弃今天的收益，保留明天的可能。','احتفظ بها لاحقاً. تتخلى عن فائدة اليوم لحفظ خيار الغد.','Guárdala para después. Renuncia al beneficio de hoy para conservar una opción mañana.','बाद के लिए रखें। कल का विकल्प बचाने को आज का लाभ छोड़ें।','Gardez-la pour plus tard. Renoncez au bénéfice présent pour préserver une option demain.','Guarde para depois. Abra mão do benefício de hoje para preservar uma opção amanhã.'),['patience'])
],
[
choice(L('بگو «آره، باید ازت می‌پرسیدم»؛ نقد شرکت را هم در پرونده نگه دار.','Say “Yes. I should have asked.” Keep the criticism of the company in the record too.','说：“是的，我应该先问你。”同时保留对公司的批评。','قل «نعم، كان يجب أن أسألك». واحتفظ أيضاً بنقد الشركة في الملف.','Di: «Sí, debí preguntarte». Conserva también la crítica a la empresa.','कहें: «हाँ, मुझे पूछना चाहिए था।» कंपनी की आलोचना भी दर्ज रखें।','Dites : «Oui, j’aurais dû te demander.» Conservez aussi la critique de l’entreprise.','Diga: “Sim, eu deveria ter perguntado.” Mantenha também a crítica à empresa.'),['accountable','evidence']),
choice(L('فقط از بسته‌شدن دکمه بگو؛ سؤال مینا بی‌پاسخ می‌ماند.','Talk only about the blocked button. Mina’s question remains unanswered.','只谈被禁用的按钮，米娜的问题仍未得到回答。','تحدث فقط عن الزر المحظور. يبقى سؤال مينا بلا جواب.','Habla solo del botón bloqueado. La pregunta de Mina queda sin respuesta.','सिर्फ़ बंद बटन की बात करें। मीना का सवाल अनुत्तरित रहेगा।','Parlez seulement du bouton bloqué. La question de Mina reste sans réponse.','Fale apenas do botão bloqueado. A pergunta de Mina fica sem resposta.'),['recovery']),
choice(L('از مینا بخواه اول حرفش را بزند؛ کنترل گفت‌وگو را تقسیم کن.','Ask Mina to speak first. Share control of the conversation.','请米娜先说，共同决定对话的方向。','اطلب من مينا أن تتكلم أولاً. تقاسما قيادة الحديث.','Pide que Mina hable primero. Comparte el control de la conversación.','मीना को पहले बोलने दें। बातचीत का नियंत्रण बाँटें।','Demandez à Mina de parler d’abord. Partagez la conduite de la conversation.','Peça a Mina para falar primeiro. Divida o controle da conversa.'),['consent','accountable'])
],[]];

export const ENDINGS=[
{id:'repayment',icon:'↗',name:L('جبران','Repaid','偿还','التعويض','Reembolso','भरपाई','Remboursé','Reembolso'),
offer:L('پول برمی‌گردد؛ اجرای محدودیت‌های دیگران به تو سپرده می‌شود.','Your money returns. You become responsible for restricting others.','钱会回来，你将负责限制他人。','يعود مالك وتصبح مسؤولاً عن تقييد الآخرين.','Vuelve tu dinero. Te encargas de restringir a otros.','पैसा लौटेगा। दूसरों पर रोक लगाना आपका काम होगा।','Votre argent revient. Vous devenez responsable des restrictions d’autrui.','Seu dinheiro volta. Você passa a restringir os outros.'),
body:L('مینا رسید انتقال را نگاه می‌کند. «ممنون که پسش دادی.» سام منتظر جملهٔ بعد است. بوق وانت می‌آید. او هنوز می‌رود. شب، پیامی می‌رسد: «چرا درخواست من متوقف شده؟» انگشت سام روی پاسخ آماده می‌ماند: «برای حفاظت از شما.» تصویر پیش از ارسال قطع می‌شود.','Mina studies the transfer. “Thank you for paying it back.” Sam waits for more. The van honks. She is still leaving. That night a message arrives: “Why was my request blocked?” His finger rests on a prepared reply: “For your protection.” The picture cuts before he sends it.','米娜看着转账记录：“谢谢你还回来。”山姆等待下一句话。货车鸣笛，她仍然要走。夜里，一条消息传来：“为什么我的请求被阻止了？”他的手指停在预设回复上：“为了保护您。”发送前，画面切黑。','تنظر مينا إلى التحويل: «شكراً لإعادته». ينتظر سام المزيد. تبوق الشاحنة؛ ما زالت سترحل. ليلاً تصل رسالة: «لماذا حُظر طلبي؟» يتوقف إصبعه على رد جاهز: «لحمايتك». تنقطع الصورة قبل الإرسال.','Mina mira la transferencia. «Gracias por devolverlo». Sam espera algo más. Suena la furgoneta. Ella se va igualmente. Esa noche: «¿Por qué bloquearon mi solicitud?». Su dedo queda sobre «Por tu protección». La imagen termina antes del envío.','मीना हस्तांतरण देखती है। «वापस देने के लिए धन्यवाद।» सैम और सुनना चाहता है। गाड़ी बजती है। वह फिर भी जा रही है। रात को संदेश: «मेरा अनुरोध क्यों रोका?» उँगली तैयार उत्तर पर है: «आपकी सुरक्षा के लिए।» भेजने से पहले दृश्य समाप्त।','Mina regarde le virement. «Merci de l’avoir rendu.» Sam attend la suite. Le camion klaxonne. Elle part quand même. Le soir : «Pourquoi ma demande a-t-elle été bloquée ?» Son doigt reste sur «Pour votre protection». L’image coupe avant l’envoi.','Mina olha a transferência. “Obrigada por devolver.” Sam espera mais. O caminhão buzina. Ela ainda vai embora. À noite: “Por que bloquearam meu pedido?” O dedo para na resposta “Para sua proteção”. A imagem corta antes do envio.')},
{id:'custodian',icon:'▣',name:L('روز بی‌حادثه','An uneventful day','平静的一天','يوم بلا حوادث','Un día sin incidentes','घटनारहित दिन','Une journée sans incident','Um dia sem incidentes'),
offer:L('مدیریت را بگیر تا از مردم محافظت کنی؛ محدودیت‌ها شامل خودت هم می‌شوند.','Take control to protect people. The restrictions will apply to you too.','接管以保护人们，限制也会适用于你。','تولّ الإدارة لحماية الناس. ستشملك القيود أيضاً.','Toma el control para proteger. Las restricciones también te afectarán.','लोगों की रक्षा के लिए नियंत्रण लें। पाबंदियाँ आप पर भी लागू होंगी।','Prenez le contrôle pour protéger. Les restrictions vous concerneront aussi.','Assuma o controle para proteger. As restrições também valem para você.'),
body:L('گزارش‌ها آرام‌تر می‌شوند. بعضی‌ها تشکر می‌کنند؛ بعضی فرصتی را از دست می‌دهند. زنی می‌نویسد: «می‌فهمم که ممکنه شکست بخورم.» سام باز هم اجازه نمی‌دهد. سال‌ها بعد، برای خروج خودش درخواست می‌دهد. دکمه خاکستری است. کسی آن طرف شیشه صلاحیت او را بررسی می‌کند.','The reports grow quieter. Some people thank you; others lose opportunities. A woman writes, “I understand I might fail.” Sam still refuses. Years later he asks to leave. His button is grey. Someone beyond the glass is assessing whether he is allowed.','报告越来越平静。有人感谢你，也有人失去机会。一位女人写道：“我知道自己可能失败。”山姆仍然拒绝。多年后，他申请离开，按钮变成灰色。玻璃另一边，有人在评估他是否获得许可。','تهدأ التقارير. بعضهم يشكرك وآخرون يفقدون فرصاً. تكتب امرأة: «أفهم أنني قد أفشل». يرفض سام مجدداً. بعد سنوات يطلب الرحيل. الزر رمادي. شخص خلف الزجاج يقيّم أهليته.','Los informes se calman. Unos agradecen; otros pierden oportunidades. Una mujer escribe: «Entiendo que puedo fracasar». Sam vuelve a negarse. Años después pide irse. Su botón está gris. Alguien tras el cristal decide si puede hacerlo.','रिपोर्ट शांत होती हैं। कुछ धन्यवाद देते हैं, कुछ मौके खोते हैं। स्त्री लिखती है: «जानती हूँ असफल हो सकती हूँ।» सैम फिर मना करता है। वर्षों बाद वह जाने का आवेदन देता है। बटन धूसर है। कोई उसकी योग्यता जाँच रहा है।','Les rapports s’apaisent. Certains remercient, d’autres perdent des occasions. Une femme écrit : «Je sais que je peux échouer.» Sam refuse encore. Des années plus tard, il demande à partir. Son bouton est gris. Derrière la vitre, quelqu’un évalue son droit de sortir.','Os relatórios ficam tranquilos. Alguns agradecem; outros perdem oportunidades. Uma mulher escreve: “Entendo que posso falhar.” Sam recusa. Anos depois, pede para sair. Seu botão está cinza. Alguém atrás do vidro avalia sua permissão.')},
{id:'fire',icon:'△',name:L('سقف سوخته','The burned roof','烧毁的屋顶','السقف المحترق','El techo quemado','जली हुई छत','Le toit brûlé','O teto queimado'),
offer:L('هسته را از کار بینداز؛ محدودیت‌ها و بعضی مدارک با هم از بین می‌روند.','Disable the core. Restrictions and some records will disappear together.','关闭核心，限制与部分记录将一同消失。','عطّل النواة. تزول القيود وبعض الأدلة معاً.','Desactiva el núcleo. Desaparecen restricciones y algunos registros.','केंद्र बंद करें। रोक और कुछ प्रमाण साथ मिटेंगे।','Désactivez le cœur. Restrictions et certains documents disparaîtront ensemble.','Desative o núcleo. Restrições e alguns registros desaparecem juntos.'),
body:L('پنجره‌ها باز می‌شوند. صدای شادی می‌آید. بعد کسی می‌پرسد: «رسید من کجاست؟» مدارک بعضی طلب‌ها هم سوخته. دارندگان نسخه‌های مستقل هنوز مدرک دارند. مینا بیرون می‌پرسد چه شد. سام می‌گوید: «خرابش کردم.» این بار جمله به‌تنهایی شبیه پیروزی نیست.','Windows open. People cheer. Then someone asks, “Where is my receipt?” Evidence of some claims burned too. Independent copies still survive. Outside, Mina asks what happened. Sam says, “I broke it.” This time the sentence does not sound like a victory on its own.','窗户打开，人们欢呼。随后有人问：“我的收据呢？”一些债权的证据也烧毁了，独立副本仍然存在。外面，米娜问发生了什么。山姆说：“我把它毁了。”这句话独自听来，并不像胜利。','تفتح النوافذ ويهتف الناس. ثم يسأل أحدهم: «أين إيصالي؟» احترقت أدلة بعض الحقوق أيضاً. بقيت النسخ المستقلة. تسأل مينا عما حدث. يقول سام: «حطمته». لا تبدو الجملة وحدها انتصاراً هذه المرة.','Se abren ventanas y suenan vítores. Luego: «¿Dónde está mi recibo?». Ardieron pruebas de algunas deudas. Las copias independientes sobreviven. Mina pregunta qué pasó. Sam dice: «Lo rompí». La frase, sola, no suena a victoria.','खिड़कियाँ खुलती हैं। खुशी के स्वर आते हैं। फिर: «मेरी रसीद कहाँ है?» कुछ दावों के प्रमाण भी जले। स्वतंत्र प्रतियाँ बचीं। मीना पूछती है क्या हुआ। सैम कहता है: «मैंने तोड़ दिया।» यह वाक्य अकेला जीत जैसा नहीं लगता।','Les fenêtres s’ouvrent. Des cris de joie, puis : «Où est mon reçu ?» Les preuves de certaines créances ont brûlé aussi. Les copies indépendantes subsistent. Mina demande ce qui s’est passé. «Je l’ai cassé.» Cette phrase seule ne sonne plus comme une victoire.','As janelas abrem. Há comemoração. Depois: “Onde está meu recibo?” Provas de algumas dívidas também queimaram. Cópias independentes sobreviveram. Mina pergunta o que houve. “Eu quebrei.” A frase sozinha não soa como vitória.')},
{id:'shared',icon:'⌘',name:L('کلیدهای پراکنده','Scattered keys','分散的钥匙','المفاتيح الموزعة','Llaves repartidas','बँटी हुई चाबियाँ','Les clés dispersées','Chaves espalhadas'),
offer:L('با سه صاحب حق توافق کن؛ اختیار تقسیم می‌شود و پول تو خودبه‌خود برنمی‌گردد.','Agree with three rights holders. Share authority without an automatic refund.','与三位权利持有者达成协议，分享权力，但钱不会自动退还。','اتفق مع ثلاثة أصحاب حقوق. تتوزع السلطة دون تعويض تلقائي.','Acuerda con tres titulares. Reparte autoridad sin reembolso automático.','तीन अधिकारधारियों से सहमति लें। अधिकार बँटेंगे, पैसा अपने आप नहीं लौटेगा।','Accordez-vous avec trois titulaires. Partagez l’autorité sans remboursement automatique.','Acorde com três titulares. Divida a autoridade sem reembolso automático.'),
body:L('همه موافق نیستند. سام حق مخالفتشان را هم نگه می‌دارد. یک نفر به‌تنهایی نمی‌تواند همه را متوقف کند. خطا و اختلاف باقی‌اند. پول سام برنمی‌گردد. برای مینا می‌نویسد: «این بار اول با تو حرف می‌زنم.» یک نمایشگر خاموش می‌شود. دو نفر برای تعمیرش می‌روند. بقیه روشن می‌مانند.','Not everyone agrees. Sam protects their right to disagree too. No single person can stop everyone. Errors and disagreements remain. His money is not returned. He writes to Mina, “This time I will talk to you first.” A monitor fails. Two people repair it. The others stay lit.','并非所有人都同意，山姆也保留他们反对的权利。没有任何一个人能让所有人停下。错误与分歧仍在，钱也没有归还。他给米娜写道：“这一次先和你谈。”一台显示器熄灭，两人去修，其他屏幕仍然亮着。','ليس الجميع موافقاً. يحفظ سام حقهم في الرفض. لا يستطيع فرد إيقاف الجميع. تبقى الأخطاء والخلافات، ولا يعود المال. يكتب لمينا: «هذه المرة أتحدث معك أولاً». تنطفئ شاشة فيذهب اثنان لإصلاحها، وتبقى البقية مضاءة.','No todos aceptan. Sam respeta también su desacuerdo. Nadie puede detener a todos. Persisten errores y conflictos. No recupera su dinero. Escribe a Mina: «Esta vez hablaré contigo primero». Se apaga un monitor; dos personas lo reparan. Los demás siguen encendidos.','सब सहमत नहीं। सैम असहमति का अधिकार भी रखता है। एक व्यक्ति सबको नहीं रोक सकता। गलतियाँ और मतभेद रहते हैं। पैसा नहीं लौटता। मीना को लिखता है: «इस बार पहले तुमसे बात करूँगा।» एक स्क्रीन बंद होती है। दो लोग उसे ठीक करते हैं। बाकी जलती रहती हैं।','Tout le monde n’est pas d’accord. Sam préserve aussi ce droit. Personne ne peut arrêter tout le monde. Erreurs et conflits demeurent. L’argent ne revient pas. Il écrit à Mina : «Cette fois, je te parlerai d’abord.» Un écran s’éteint. Deux personnes le réparent. Les autres restent allumés.','Nem todos concordam. Sam preserva esse direito também. Ninguém pode parar todos sozinho. Erros e conflitos continuam. O dinheiro não volta. Escreve a Mina: “Desta vez, falo com você primeiro.” Um monitor apaga. Duas pessoas o consertam. Os outros seguem acesos.')},
{id:'leave',icon:'↵',name:L('رسید باز','The open receipt','未结的收据','الإيصال المفتوح','El recibo abierto','खुली रसीद','Le reçu ouvert','O recibo aberto'),
offer:L('از بازار برو؛ بدهی باقی می‌ماند و اختیار خودت را نگه می‌داری.','Leave the market. The debt remains; your decisions remain yours.','离开市场。债务仍在，但选择仍属于你。','غادر السوق. يبقى الدين وتبقى قراراتك لك.','Abandona el mercado. La deuda permanece; las decisiones siguen siendo tuyas.','बाज़ार छोड़ें। कर्ज रहेगा, निर्णय आपके रहेंगे।','Quittez le marché. La dette demeure, vos décisions vous appartiennent.','Saia do mercado. A dívida permanece; as decisões continuam suas.'),
body:L('غذا کنار در سرد شده. بدهی هست. مینا حساب مشترک تازه‌ای باز نمی‌کند. سام می‌گوید: «باید قبلش ازت می‌پرسیدم.» مینا: «آره.» آخرین تصویر، دو نفرند که وسیله‌ای سنگین را از دری باریک رد می‌کنند. یکی صبر می‌کند تا دیگری زاویه‌اش را عوض کند.','The food by the door is cold. The debt remains. Mina opens no new joint account. Sam says, “I should have asked you first.” “Yes.” In the last frame, two people carry something heavy through a narrow door. One waits while the other changes their angle.','门口的饭已经凉了。债务仍在，米娜也不会新开共同账户。山姆说：“我应该先问你。”她答：“是的。”最后一幕，两人搬着重物穿过窄门，一人等待另一人调整角度。','برد الطعام عند الباب. بقي الدين، ولم تفتح مينا حساباً مشتركاً جديداً. يقول سام: «كان يجب أن أسألك أولاً». «نعم». في آخر مشهد يحملان شيئاً ثقيلاً عبر باب ضيق. ينتظر أحدهما ليغير الآخر زاويته.','La comida está fría. Sigue la deuda. Mina no abre otra cuenta común. «Debí preguntarte». «Sí». En el último plano, dos personas pasan algo pesado por una puerta estrecha. Una espera a que la otra cambie de ángulo.','दरवाज़े का खाना ठंडा है। कर्ज बाकी है। मीना नया साझा खाता नहीं खोलती। सैम: «पहले पूछना चाहिए था।» «हाँ।» अंतिम दृश्य में दो लोग भारी वस्तु सँकरे दरवाज़े से निकालते हैं। एक रुकता है ताकि दूसरा कोण बदल सके।','Le repas est froid. La dette reste. Mina n’ouvre pas de nouveau compte commun. «J’aurais dû te demander.» «Oui.» Dernière image : deux personnes passent un objet lourd dans une porte étroite. L’une attend que l’autre change d’angle.','A comida está fria. A dívida continua. Mina não abre outra conta conjunta. “Eu deveria ter perguntado.” “Sim.” Na última imagem, duas pessoas passam algo pesado por uma porta estreita. Uma espera a outra mudar de ângulo.')},
{id:'autopilot',icon:'∅',name:L('دست‌های راحت','Unburdened hands','轻松的双手','الأيدي المرتاحة','Manos sin carga','बोझमुक्त हाथ','Les mains légères','Mãos despreocupadas'),
offer:L('انتخاب‌های شخصی را برای همیشه واگذار کن؛ سود یا خوشبختی تضمین نمی‌شود.','Permanently delegate personal decisions. Neither profit nor happiness is guaranteed.','永久委托个人决定，收益和幸福均不保证。','فوّض قراراتك الشخصية نهائياً. لا ضمان للربح أو السعادة.','Delega tus decisiones para siempre. No se garantizan beneficios ni felicidad.','व्यक्तिगत निर्णय हमेशा के लिए सौंपें। लाभ या खुशी की गारंटी नहीं।','Déléguez définitivement vos décisions personnelles. Ni profit ni bonheur ne sont garantis.','Delegue decisões pessoais para sempre. Lucro ou felicidade não são garantidos.'),
body:L('زندگی ادامه دارد. بعضی تصمیم‌های صندوق خوب‌اند، بعضی بد. اما پیش از تردید، انتخاب اجرا می‌شود. روزی مینا سازی را برای سام می‌نوازد. «خوشت اومد؟» دو پاسخ ظاهر می‌شود. نشانگر خودش انتخاب می‌کند: «خیلی.» مینا لبخند می‌زند. سام نمی‌داند پاسخ خودش چه بود.','Life continues. Some decisions are good, others bad, but they happen before doubt arrives. One day Mina plays an instrument for Sam. “Did you like it?” Two answers appear. The cursor chooses on its own: “Very much.” Mina smiles. Sam does not know what his own answer was.','生活继续。有些决定好，有些坏，但犹豫前就已执行。某天米娜为山姆演奏：“喜欢吗？”两个回答出现，光标自行选择：“非常喜欢。”米娜笑了。山姆不知道自己的答案是什么。','تستمر الحياة. بعض القرارات جيد وبعضها سيئ، لكنها تُنفذ قبل التردد. تعزف مينا وتسأل: «أعجبك؟» يظهر جوابان. يختار المؤشر وحده: «كثيراً». تبتسم مينا. لا يعرف سام ما كان جوابه.','La vida sigue. Hay decisiones buenas y malas, tomadas antes de la duda. Mina toca un instrumento. «¿Te gustó?». Aparecen dos respuestas. El cursor elige solo: «Mucho». Mina sonríe. Sam no sabe cuál era su propia respuesta.','जीवन चलता है। कुछ निर्णय अच्छे, कुछ बुरे, पर संदेह से पहले हो जाते हैं। मीना संगीत बजाती है। «पसंद आया?» दो उत्तर आते हैं। कर्सर खुद चुनता है: «बहुत।» मीना मुस्कुराती है। सैम अपना उत्तर नहीं जानता।','La vie continue. Certaines décisions sont bonnes, d’autres mauvaises, prises avant le doute. Mina joue d’un instrument. «Tu as aimé ?» Deux réponses apparaissent. Le curseur choisit seul : «Beaucoup.» Mina sourit. Sam ignore sa propre réponse.','A vida continua. Há decisões boas e ruins, tomadas antes da dúvida. Mina toca um instrumento. “Gostou?” Duas respostas aparecem. O cursor escolhe sozinho: “Muito.” Mina sorri. Sam não sabe qual era sua resposta.')}
];

ENDINGS.push(...EXTRA_ENDINGS,...NEW_ENDINGS);
const TYPES=[['circuit','memory','code'],['lights','ledger','code'],['circuit','memory','ledger'],['circuit','lights','ledger'],['code','circuit','memory'],['memory','lights','ledger'],['ledger','code','circuit'],['ledger','memory','code']];
export const AFTERMATH={
 acknowledged:L('چون پیش‌تر مسئولیتت را پذیرفتی، مینا اجازه می‌دهد در جابه‌جایی کمک کنی. بازپرداخت، مرزهای تازه‌اش را عوض نکرده است.','Because you acknowledged your part earlier, Mina lets you help with the move. Repayment has not changed her new boundaries.','因为你之前承认了自己的责任，米娜让你帮忙搬家。还款没有改变她新设立的界限。','لأنك اعترفت بمسؤوليتك سابقاً، تسمح مينا بمساعدتها في النقل. التعويض لم يغير حدودها الجديدة.','Como reconociste tu responsabilidad, Mina te deja ayudar con la mudanza. El reembolso no cambia sus nuevos límites.','पहले ज़िम्मेदारी मानने पर मीना आपको सामान ले जाने में मदद करने देती है। भुगतान उसकी नई सीमाएँ नहीं बदलता।','Comme vous avez reconnu votre part, Mina vous laisse aider au déménagement. Le remboursement ne change pas ses limites.','Por reconhecer sua responsabilidade antes, Mina deixa você ajudar na mudança. O reembolso não muda os limites dela.'),
 unanswered:L('سؤال قبلی مینا بی‌پاسخ مانده بود. او رسید انتقال را می‌گیرد، اما برای حرف‌زدن امشب آمادگی ندارد.','Mina’s earlier question was left unanswered. She accepts the transfer receipt, but is not ready to talk tonight.','米娜之前的问题没有得到回答。她收下转账凭证，但今晚还不愿交谈。','بقي سؤال مينا السابق بلا جواب. تقبل إيصال التحويل، لكنها غير مستعدة للحديث الليلة.','La pregunta de Mina quedó sin respuesta. Acepta el recibo, pero no está lista para hablar esta noche.','मीना का पिछला सवाल अनुत्तरित था। वह भुगतान की रसीद लेती है, पर आज बात के लिए तैयार नहीं।','La question de Mina était restée sans réponse. Elle accepte le reçu, mais ne veut pas parler ce soir.','A pergunta de Mina ficou sem resposta. Ela aceita o recibo, mas não está pronta para conversar hoje.'),
 copies:L('مدارکی که در تصمیم‌های قبلی حفظ کردی حالا به بازسازی بخشی از حق‌ها کمک می‌کنند. سوختن مرکز، همهٔ نسخه‌ها را از بین نبرده است.','Evidence you preserved earlier now helps reconstruct some claims. Burning the center did not destroy every copy.','你之前保留的证据有助于重建部分权利。中心被烧毁，并不意味着所有副本都消失。','تساعد الأدلة التي حفظتها سابقاً في إعادة إثبات بعض الحقوق. احتراق المركز لم يدمر كل النسخ.','Las pruebas que conservaste ayudan a reconstruir derechos. El incendio no destruyó todas las copias.','पहले सुरक्षित किए प्रमाण कुछ अधिकार फिर साबित करने में मदद करते हैं। केंद्र जलने से सारी प्रतियाँ नहीं मिटीं।','Les preuves conservées aident à rétablir certaines créances. L’incendie n’a pas détruit toutes les copies.','As provas preservadas ajudam a reconstruir direitos. O incêndio não destruiu todas as cópias.'),
 missing:L('در تصمیم‌های قبلی مدارک مستقل کمتری نگه داشتی. بازسازی بعضی حق‌ها اکنون به شهادت دیگران وابسته است.','You kept fewer independent records in earlier decisions. Reconstructing some claims now depends on other people’s testimony.','你之前保留的独立记录较少。现在重建部分权利需要依赖他人的证词。','احتفظت بسجلات مستقلة أقل. إثبات بعض الحقوق يعتمد الآن على شهادات الآخرين.','Guardaste menos pruebas independientes. Reconstruir algunos derechos depende de otros testimonios.','पहले स्वतंत्र अभिलेख कम रखे थे। कुछ दावों का पुनर्निर्माण अब दूसरों की गवाही पर निर्भर है।','Vous avez conservé moins de documents indépendants. Certaines créances dépendent maintenant des témoignages d’autrui.','Você guardou menos registros independentes. Alguns direitos agora dependem do testemunho de outras pessoas.')
};
const ERAS=['2026 · NEW JERSEY','— · THE FIRST EXCHANGE','1984 / 1994 · THE EARLY WEB','2008 · THE PAPER HOUSE','2008 / 2009 · GENESIS','2010 · A TABLE FOR TWO','2021 · THE BUY BUTTON','2026 · THE UNFINISHED MARKET'];
export const CHAPTERS=TITLES.map((name,index)=>{
 const shifts=[0,25,-15,20,-25,15,0,-10];const shift=shifts[index];
 const stations=[[220+shift,191],[746-shift,283],[440+shift,452]].map(([x,y],i)=>({id:`${index}:s${i}`,type:'station',x,y,puzzle:TYPES[index][i],slot:i}));
 const records=[[105,338],[810,480],[780,127],[307,542]].map(([x,y],i)=>({id:`${index}:r${i}`,type:'record',x:x+(i%2?shift:0),y,slot:i}));
 const props=[{type:'shelf',x:65,y:95,w:74,h:63},{type:'shelf',x:395,y:95,w:68,h:51},{type:'crate',x:160,y:365,w:57,h:39},{type:'table',x:635,y:443,w:73,h:39},{type:'plant',x:905,y:178,solid:false},{type:'plant',x:65,y:450,solid:false},{type:'lamp',x:566,y:184,solid:false},{type:index===4?'server':'shelf',x:527,y:315,w:50,h:91},{type:index===3?'water':'crate',x:328,y:245,w:71,h:46,solid:index!==3},{type:index===4?'server':'shelf',x:877,y:337,w:37,h:70}];
 if(index%2)props.push({type:index===4?'server':'crate',x:613,y:160,w:53,h:74});
 return applyLayout({index,name,era:ERAS[index],intro:INTROS[index],records:RECORDS[index],choices:CHOICES[index],props,entities:[...stations,...records,{id:`${index}:npc`,type:'npc',x:492,y:210,kind:index===7?'cashier':index===5||index===0?'mina':index===4?'sage':'trader'},{id:`${index}:exit`,type:'exit',x:860,y:105}],start:{x:110,y:536}});
});
