import {L,ORDER} from './i18n.js';

const localize=values=>Object.fromEntries(ORDER.map((lang,index)=>[lang,values[index]??values[1]??'']));
const note=(id,title,body)=>({id,title:L(...title),body:L(...body)});

export const DETAIL_UI={
 kicker:L('ردپای پنهان','HIDDEN TRACE','隐藏线索','أثر خفي','Rastro oculto','छुपा सुराग','Trace cachée','Rastro oculto'),
 found:L('ردپا ثبت شد','Trace recorded','线索已记录','تم تسجيل الأثر','Rastro registrado','सुराग दर्ज','Trace enregistrée','Rastro registado'),
 archive:L('آرشیو جزئیات','Detail archive','线索档案','أرشيف التفاصيل','Archivo de detalles','विवरण संग्रह','Archives des détails','Arquivo de detalhes'),
 archiveHelp:L('هر برگه گوشه‌ای از اقتصاد، ترس و انتخاب‌های این جهان را نگه می‌دارد.','Every scrap keeps a piece of this world’s economy, fear and choices.','每张纸片都保存着这个世界的经济、恐惧与选择。','كل قصاصة تحفظ جزءاً من اقتصاد العالم وخوفه واختياراته.','Cada fragmento guarda economía, miedo y decisiones.','हर टुकड़ा इस दुनिया की अर्थव्यवस्था, डर और चुनाव सँभालता है।','Chaque fragment conserve l’économie, la peur et les choix du monde.','Cada pedaço guarda a economia, o medo e as escolhas deste mundo.'),
 empty:L('هنوز چیزی پیدا نکرده‌ای. به علامت‌های کوچک نزدیک شو.','Nothing found yet. Follow the small marks.','还没有发现。跟随细小的标记。','لم تكتشف شيئاً بعد. اتبع العلامات الصغيرة.','Aún no hay nada. Sigue las pequeñas marcas.','अभी कुछ नहीं मिला। छोटे निशानों का पीछा करें।','Rien trouvé. Suivez les petits signes.','Nada encontrado. Siga as pequenas marcas.'),
 count:L('{n} / {total} ردپا','{n} / {total} traces','{n} / {total} 条线索','{n} / {total} أثر','{n} / {total} rastros','{n} / {total} सुराग','{n} / {total} traces','{n} / {total} rastros')
};

const seeds=[
 ['چراغ فردا','Tomorrow’s lamp','明日的灯','مصباح الغد','La lámpara de mañana','कल का दीपक','La lampe de demain','A lâmpada de amanhã','یک چراغ کوچک روی میز مانده؛ کسی هزینهٔ روشن ماندنش را حساب نکرده است.','A small lamp remains; no one priced its light.','桌上留着一盏小灯；没人给光定价。','مصباح صغير باقٍ؛ لم يسعّر أحد نوره.','Una lámpara queda; nadie puso precio a su luz.','छोटा दीपक बचा; रोशनी की कीमत नहीं लगी।','Une lampe reste ; personne n’a fixé son prix.','Uma lâmpada ficou; ninguém deu preço à luz.'],
 ['دست و دفتر','Hand and ledger','手与账本','اليد والدفتر','Mano y libro','हाथ और बही','Main et registre','Mão e livro','جوهر معامله در دستی است که آن را امضا می‌کند.','A deal lives in the hand that signs it.','交易活在签字的手里。','الصفقة في اليد التي توقع.','El trato vive en la mano que firma.','सौदा हस्ताक्षर वाले हाथ में है।','Le marché vit dans la main qui signe.','O acordo vive na mão que assina.'],
 ['فاصلهٔ دو دست','Distance between hands','双手之间','المسافة بين يدين','Distancia entre manos','दो हाथों की दूरी','Distance entre deux mains','Distância entre mãos','هر فاصله هم راه سوءتفاهم است هم راه اعتماد.','Every distance can confuse or build trust.','每段距离都可能误解，也可能信任。','كل مسافة قد تربك أو تبني الثقة.','Toda distancia confunde o crea confianza.','हर दूरी भ्रम या भरोसा है।','Chaque distance trouble ou crée la confiance.','Toda distância confunde ou cria confiança.'],
 ['خانهٔ کاغذی','Paper house','纸屋','البيت الورقي','Casa de papel','कागज़ का घर','Maison de papier','Casa de papel','دیوارها کاغذند، اما تصمیم‌های پشتشان واقعی است.','The walls are paper; the decisions are real.','墙是纸，决定却真实。','الجدران ورق والقرارات حقيقية.','Las paredes son papel; las decisiones son reales.','दीवारें कागज़, फैसले असली।','Les murs sont papier, les décisions réelles.','As paredes são papel; decisões são reais.'],
 ['نام بی‌صاحب','Name without an owner','无主之名','اسم بلا مالك','Nombre sin dueño','बिना मालिक का नाम','Nom sans propriétaire','Nome sem dono','وقتی نام صاحب ناپدید می‌شود، مسئولیت به تو می‌رسد.','When an owner vanishes, responsibility reaches you.','所有者消失，责任来到你手上。','حين يختفي المالك تصل المسؤولية إليك.','Si el dueño desaparece, la responsabilidad llega.','मालिक मिटे तो जिम्मेदारी आती है।','Quand le propriétaire disparaît, la responsabilité arrive.','Quando o dono some, a responsabilidade chega.'],
 ['دو سفارش','Two orders','两份订单','طلبان','Dos pedidos','दो आदेश','Deux commandes','Dois pedidos','دو سفارش روی یک میز نشسته‌اند و هر دو می‌گویند اول بوده‌اند.','Two orders share a desk; both claim to be first.','两份订单都说自己先到。','طلبان يدعيان أنهما الأول.','Dos pedidos dicen ser primeros.','दोनों आदेश खुद को पहला कहते हैं।','Deux commandes se disent premières.','Dois pedidos dizem ser primeiros.'],
 ['اتاق تسویه','Clearing room','清算室','غرفة التسوية','Sala de compensación','निपटान कक्ष','Salle de compensation','Sala de compensação','تسویه عدد نیست؛ حافظه‌ای است که می‌گوید چه کسی چه پذیرفت.','Clearing remembers who accepted what.','结算记得谁接受了什么。','التسوية تتذكر من قبل ماذا.','Liquidar recuerda quién aceptó qué.','निपटान याद रखता है किसने क्या माना।','La compensation se souvient des accords.','A liquidação lembra quem aceitou o quê.'],
 ['آخرین رسید','The last receipt','最后的收据','الإيصال الأخير','El último recibo','आख़िरी रसीद','Le dernier reçu','O último recibo','آخرین رسید سفید است؛ جای امضای تصمیم تو خالی مانده.','The last receipt is blank; its signature awaits you.','最后的收据空白，等你签名。','الإيصال الأخير فارغ وينتظر توقيعك.','El recibo final espera tu firma.','आख़िरी रसीद आपके हस्ताक्षर की राह देखती है।','Le dernier reçu attend votre signature.','O último recibo espera sua assinatura.']
];
export const CHAPTER_DETAILS=seeds.map((seed,chapter)=>[note(`chapter:${chapter}:d0`,seed.slice(0,8),seed.slice(8))]);
export const COMMONS_DETAILS=[
 note('commons:d0',['تابلوی جاده','Road board','道路公告板','لوحة الطريق','Tablero','सड़क बोर्ड','Panneau de route','Quadro da estrada'],['هر مسیر با یک تصمیم شروع می‌شود، حتی اگر مقصد را ندانی.','Every road starts with a decision, even when the destination is unknown.','每条路都从决定开始，即使不知道目的地。','كل طريق يبدأ بقرار ولو جهلت وجهته.','Cada camino empieza con una decisión.','हर राह फैसले से शुरू होती है।','Chaque route commence par une décision.','Toda estrada começa com uma decisão.']),
 note('commons:d1',['دکمه‌ای زیر خاک','A button under soil','土下的按钮','زر تحت التراب','Un botón bajo tierra','मिट्टी का बटन','Un bouton sous la terre','Um botão sob a terra'],['خاک کنار دیوار می‌لرزد؛ دکمه‌ای روشن هنوز کسی را صدا می‌زند.','Soil moves beside the wall; a lit button still calls someone.','墙边的土在动；亮着的按钮仍在呼唤。','تتحرك التربة؛ زر مضاء ما زال ينادي.','La tierra se mueve; un botón llama.','मिट्टी हिलती है; जला बटन बुलाता है।','La terre bouge ; un bouton appelle.','A terra se move; um botão chama.'])
];

export const DETAIL_IDS=[...CHAPTER_DETAILS.flat(),...COMMONS_DETAILS].map(item=>item.id);
const allDetails=[...CHAPTER_DETAILS.flat(),...COMMONS_DETAILS];
export function detailFor(id){return allDetails.find(item=>item.id===id)||null;}
export function placeChapterDetails(chapter,index){const anchor=chapter.entities.find(entity=>entity.type==='record')||chapter.start;return CHAPTER_DETAILS[index].map(note=>({id:note.id,type:'detail',x:Math.max(48,Math.min((chapter.width||960)-48,anchor.x+28)),y:Math.max(90,Math.min((chapter.height||640)-50,anchor.y+16)),slot:0}));}
export function placeCommonsDetails(){return COMMONS_DETAILS.map((note,slot)=>({id:note.id,type:'detail',x:slot?1710:125,y:slot?1120:590,slot}));}
