import {LANGUAGES,UI,tr,setLanguage,getLanguage,direction} from './i18n.js';
import {CHAPTERS,ENDINGS,SOURCES,AFTERMATH} from './content.js';
import {newState,readSave,writeSave,readSettings,validateState,SETTINGS_KEY,chapterDone,addDecision,addEpisodeDecision,decisionEvents,reflectionCounts,canChooseEnding,recordEnding,resumeBeforeEnding} from './state.js';
import {Engine} from './engine.js';
import {drawTitle,character} from './art.js';
import {Soundscape} from './audio.js';
import {PuzzleUI,puzzleName} from './puzzle-ui.js';
import {h,button} from './dom.js';
import {EPISODES} from './episodes.js';
import {D} from './director-text.js';
import {EpisodeUI} from './episode-ui.js';
import {renderEndingOffers,renderFinale,renderEndingGallery} from './ending-ui.js';
import {ET} from './ending-text.js';
import {ENDING_ROUTES} from './ending-rules.js';
import {renderReflection} from './reflection-ui.js';
import {COMMONS,canVisitChapter,enterChapter,returnToCommons,discover,projectCount,finishProject,ringBell,settledChapters} from './open-world.js';
import {W,POSTCARDS} from './world-text.js';
import {renderAtlas} from './world-ui.js';
import {MusicUI} from './music-ui.js';
import {MT,TRACK_NAMES} from './music-text.js';
const $=id=>document.getElementById(id);
let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw new Error('Storage disabled');}};}
let settings=readSettings(storage),state=readSave(storage),playing=false,modalOpen=false,clockPaused=false,puzzle=null,episodeUI=null,musicUI=null,modalBuilder=null,previousFocus=null,saveOK=true,toastTimer,titleLast=0,session=0,hudSignature='',bannerTimer;
const audio=new Soundscape();audio.on=settings.sound;audio.volume=settings.volume;audio.mix(settings.musicVolume,settings.effectsVolume);audio.setPattern(settings.musicPattern);
const engine=new Engine($('world'),{settings,onInteract:interact,onHud:updateHUD,onCaught:()=>toast(tr('caught')),onShadow:kind=>{if(kind==='near')toast(tr(D.hideHelp));else audio.tone('ward');},onEvent:kind=>{toast(tr(D[kind+'Cue']));audio.tone('paper');save();},onStep:quiet=>audio.step(quiet),getBeat:()=>audio.transport()});
function tnode(tag,key,cls){return h(tag,{class:cls||''},tr(key));}
function storeSettings(){try{storage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{}}
function save(){if(!state)return;saveOK=writeSave(storage,state);$('save-label').textContent=tr(saveOK?'saved':'savingError');$('save-indicator').style.background=saveOK?'':'#ee8d7f';$('continue-game').hidden=!state;}
function translate(){setLanguage(settings.language);document.documentElement.lang=getLanguage()==='zh'?'zh-Hans':getLanguage();document.documentElement.dir=direction();document.title=tr('titleA')+' '+tr('titleB')+' · THE LAST BUYER';document.body.classList.toggle('reduced-motion',settings.reducedMotion);document.documentElement.style.setProperty('--text-scale',settings.textSize);document.querySelectorAll('[data-t]').forEach(el=>el.textContent=tr(el.dataset.t));$('gallery').textContent=tr(ET.title);$('ending-total').textContent=String(ENDINGS.length).padStart(2,'0');$('music-room').textContent=tr(MT.title);$('music-hud').setAttribute('aria-label',tr(MT.title));$('focus-mode').setAttribute('aria-label',tr(D.focus));$('focus-mode').title=tr(D.focus);$('objective-toggle').setAttribute('aria-label',tr(W.tasks));$('journal').setAttribute('aria-label',tr('journal'));$('map-btn').setAttribute('aria-label',tr(W.atlas));$('return-commons').setAttribute('aria-label',tr(W.return));$('floating-map-button').setAttribute('aria-label',tr(W.atlas));$('crouch-label').textContent=tr(D.crouch);$('language').value=settings.language;$('language').setAttribute('aria-label',tr('language'));$('sound').setAttribute('aria-label',tr('sound'));$('settings').setAttribute('aria-label',tr('settings'));$('pause').setAttribute('aria-label',tr('pauseTitle'));$('modal-close').setAttribute('aria-label',tr('close'));$('world').setAttribute('aria-label',tr('move')+' · '+tr('interact'));$('touch-interact').setAttribute('aria-label',tr('interact'));document.querySelector('.mission-panel').dir=direction();$('sound').textContent=settings.sound?'♪':'♩';$('sound').setAttribute('aria-pressed',settings.sound);if(playing)updateHUD();}
for(const lang of LANGUAGES)$('language').append(h('option',{value:lang.id},lang.name));
$('language').addEventListener('change',()=>{settings.language=$('language').value;storeSettings();translate();});
$('sound').addEventListener('click',()=>{settings.sound=!settings.sound;audio.set(settings.sound,settings.volume);storeSettings();translate();});
$('settings').addEventListener('click',showSettings);$('pause').addEventListener('click',showPause);$('journal').addEventListener('click',()=>showJournal());$('map-btn').addEventListener('click',showMap);$('hint').addEventListener('click',()=>openModal(root=>{const outdoors=state.zone==='commons';root.append(tnode('div','hint','modal-kicker'),h('h2',{},tr(outdoors?W.title:CHAPTERS[state.chapter].name)),h('p',{class:'body-copy'},tr(outdoors?W.intro:'hintBody')));if(!outdoors)root.append(h('p',{class:'modal-note'},tr(D.episodeFirst)),h('p',{class:'modal-note'},tr(D.hideHelp)));root.append(h('div',{class:'modal-actions'},...(outdoors?[button(tr(W.atlas),showMap)]:[]),button(tr('next'),closeModal,'btn primary')));}));
$('about').addEventListener('click',()=>openModal(root=>{root.append(tnode('div','edition','modal-kicker'),tnode('h2','about'),tnode('p','aboutBody','body-copy'));for(const source of SOURCES)root.append(h('div',{class:'journal-entry'},h('a',{href:source.url,target:'_blank',rel:'noopener noreferrer'},source.title)));}));
$('brand').addEventListener('click',e=>{e.preventDefault();if(playing)showPause();});
$('new-game').addEventListener('click',()=>{audio.start();if(state)openModal(root=>root.append(tnode('h2','newGame'),tnode('p','overwrite','body-copy'),h('div',{class:'modal-actions'},button(tr('export'),exportSave),button(tr('cancel'),closeModal),button(tr('newGame'),beginNew,'btn primary'))));else beginNew();});
$('continue-game').addEventListener('click',()=>{audio.start();if(!state)return;enterGame();loadChapter(false);if(state.ending)showEnding(state.ending);});
function beginNew(){closeModal();session++;state=newState(state?.collection||[],state?.endingRecords||{});save();enterGame();loadChapter(false);openModal(root=>{root.append(tnode('div','edition','modal-kicker'),tnode('h2','startTitle'),tnode('p','startBody','body-copy'),h('div',{class:'onboarding-keys'},h('span',{},h('kbd',{},'W A S D'),tr('move')),h('span',{},h('kbd',{},'E'),tr('interact')),h('span',{},h('kbd',{},'SPACE'),tr('ward'))),tnode('p','startNote','modal-note'),h('div',{class:'modal-actions'},button(tr('settings'),showSettings),button(tr('newGame'),()=>{closeModal();showChapterIntro();},'btn primary')));},{clock:true});}
function enterGame(){playing=true;document.body.classList.add('playing');$('menu').hidden=true;$('game').hidden=false;engine.active=true;audio.set(settings.sound,settings.volume);window.scrollTo({top:0,behavior:'instant'});}
function loadChapter(intro=true){const location=state.zone==='commons'?COMMONS:CHAPTERS[state.chapter];engine.load(location,state);document.body.classList.toggle('in-commons',state.zone==='commons');audio.chapter(state.zone==='commons'?8:state.chapter);engine.setPaused(false);hudSignature='';updateHUD();save();$('world').focus({preventScroll:true});clearTimeout(bannerTimer);$('chapter-banner').textContent=state.zone==='commons'?tr(W.title):tr(D.level)+' '+(state.chapter+1)+' · '+tr(CHAPTERS[state.chapter].name);$('chapter-banner').hidden=false;bannerTimer=setTimeout(()=>{$('chapter-banner').hidden=true;},4200);if(intro)showChapterIntro();}
function showChapterIntro(){const outdoors=state.zone==='commons',chapter=outdoors?COMMONS:CHAPTERS[state.chapter];openModal(root=>{root.append(h('div',{class:'modal-kicker',dir:'ltr'},outdoors?chapter.era:`${String(chapter.index+1).padStart(2,'0')} / 08 · ${chapter.era}`),h('h2',{},tr(chapter.name)),h('p',{class:'body-copy'},tr(chapter.intro)),h('div',{class:'modal-actions'},button(tr('next'),closeModal,'btn primary')));},{clock:false});}
function titleScreen(){document.body.classList.remove('immersive','playing','objectives-open');$('focus-mode').setAttribute('aria-pressed','false');closeModal();playing=false;engine.active=false;engine.setPaused(true);save();$('menu').hidden=false;$('game').hidden=true;$('continue-game').hidden=!state;audio.suspend(false);$('continue-game').focus();}
function openModal(builder,{clock=true}={}){if(!modalOpen)previousFocus=document.activeElement;puzzle?.dispose();puzzle=null;episodeUI?.dispose();episodeUI=null;musicUI?.dispose();musicUI=null;modalBuilder=builder;modalOpen=true;clockPaused=clock;engine.setPaused(true);$('interaction-prompt').hidden=true;$('modal-backdrop').hidden=false;$('app').inert=true;$('modal-content').replaceChildren();builder($('modal-content'));$('modal').focus({preventScroll:true});}
function closeModal(){puzzle?.dispose();puzzle=null;episodeUI?.dispose();episodeUI=null;musicUI?.dispose();musicUI=null;modalBuilder=null;modalOpen=false;clockPaused=false;$('modal-backdrop').hidden=true;$('app').inert=false;engine.setPaused(!playing||document.hidden);save();if(playing){$('world').focus({preventScroll:true});updateHUD();}else if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});}
function dismissModal(){if(playing&&state?.ending)titleScreen();else closeModal();}
$('modal-close').addEventListener('click',dismissModal);
document.addEventListener('keydown',e=>{if(modalOpen){if(e.code==='Escape'){e.preventDefault();dismissModal();return;}if(e.code==='Tab'){const nodes=[...$('modal').querySelectorAll('button:not(:disabled),a[href],input,select,textarea,summary,[tabindex="0"]')].filter(el=>!el.hidden);if(!nodes.length){e.preventDefault();return;}const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('modal'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===$('modal'))){e.preventDefault();first.focus();}}return;}if(!playing||e.target.matches('input,select,textarea'))return;if(e.code==='Escape'){e.preventDefault();showPause();}if(e.code==='KeyJ'){e.preventDefault();showJournal();}if(e.code==='KeyM'){e.preventDefault();showMap();}});
document.addEventListener('visibilitychange',()=>{engine.setPaused(document.hidden||modalOpen||!playing);audio.suspend(document.hidden);if(document.hidden)save();});
window.addEventListener('pagehide',save);
for(const b of document.querySelectorAll('[data-dir]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);engine.touch(b.dataset.dir,true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>engine.touch(b.dataset.dir,false));}
$('touch-interact').addEventListener('click',()=>engine.interact());
$('touch-crouch').addEventListener('click',()=>engine.toggleCrouch());
$('gallery').addEventListener('click',showGallery);$('music-room').addEventListener('click',showMusic);$('music-hud').addEventListener('click',showMusic);$('return-commons').addEventListener('click',goCommons);$('floating-map-button').addEventListener('click',showMap);$('objective-toggle').addEventListener('click',()=>{const open=document.body.classList.toggle('objectives-open');$('objective-toggle').setAttribute('aria-expanded',String(open));});$('focus-mode').addEventListener('click',()=>{const active=document.body.classList.toggle('immersive');$('focus-mode').setAttribute('aria-pressed',String(active));$('world').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});});
$('touch-ward').addEventListener('click',()=>{engine.ward();updateHUD();});
$('touch-run').addEventListener('pointerdown',e=>{e.preventDefault();$('touch-run').setPointerCapture(e.pointerId);engine.keys.add('ShiftLeft');});
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('touch-run').addEventListener(event,()=>engine.keys.delete('ShiftLeft'));
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>{$('toast').hidden=true;},4200);}
function updateHUD(){
 if(!state||!playing)return;
 const ch=state.zone==='commons'?COMMONS:CHAPTERS[state.chapter],signature=[state.zone,ch.index,getLanguage(),state.solved.join(','),state.records.join(','),state.episodes.join(','),state.discoveries.join(','),state.projects.join(','),state.tracked,Object.keys(state.decisions).join(','),saveOK].join('|');
 // Narrative DOM changes only when the data changes, independently of render FPS.
 if(signature!==hudSignature){
  hudSignature=signature;
  $('chapter-no').textContent=String(ch.index+1).padStart(2,'0');$('chapter-era').textContent=ch.era;
  $('chapter-name').textContent=tr(ch.name);$('location').textContent=tr(ch.name);$('objective-title').textContent=tr(ch.name);
  $('objective-desc').textContent=chapterDone(state,ch.index)?tr(ch.index===7?'decision':'exit'):state.episodes.includes(ch.index)?tr('locked'):tr(D.episodeFirst);
  $('objective-list').replaceChildren(h('li',{class:'scene-objective '+(state.episodes.includes(ch.index)?'done':'')},'◉ '+tr(EPISODES[ch.index].title)),...ch.entities.filter(e=>e.type==='station').map(e=>h('li',{class:state.solved.includes(e.id)?'done':''},ch.index===7?tr('consent')+' '+(e.slot+1):puzzleName(e.puzzle))));
  const tasks=ch.entities.filter(e=>e.type==='station'&&state.solved.includes(e.id)).length+Number(state.episodes.includes(ch.index));$('level-progress').style.width=tasks*25+'%';$('level-progress-label').textContent=tasks+' / 4';$('minimap-label').textContent=tr(D.investigate)+' ◉';
  $('receipt-count').textContent=state.records.length+'/32';
  $('inventory-icons').replaceChildren(...Array.from({length:4},(_,i)=>h('span',{class:'inventory-item '+(state.records.includes(`${ch.index}:r${i}`)?'':'empty'),'aria-label':tr('echo')+' '+(i+1)},state.records.includes(`${ch.index}:r${i}`)?'▤':'·')));
  $('save-label').textContent=tr(saveOK?'saved':'savingError');
  if(state.zone==='commons'){const done=settledChapters(state);$('chapter-no').textContent='∞';$('objective-desc').textContent=tr(W.explore);$('objective-list').replaceChildren(...[[W.workshop,'lights','fuse'],[W.mailbox,'letters','postcard'],[W.melody,'melody',null]].map(([label,id,item])=>h('li',{class:state.projects.includes(id)?'done':''},tr(label)+' · '+(item?projectCount(state,item)+'/3':state.projects.includes(id)?'4/4':state.bellSequence.length+'/4'))));$('level-progress').style.width=done.length/7*100+'%';$('level-progress-label').textContent=done.length+' / 7';$('minimap-label').textContent=tr(W.atlas);}
 }
 audio.updateWorld({intensity:engine.threat==='hunted'?1:0,discovery:state.projects.length});$('music-track-name').textContent=tr(TRACK_NAMES[audio.trackIndex]);$('music-hud').classList.toggle('muted',!audio.on);
 $('composure-num').textContent=Math.round(engine.composure)+'%';$('composure-meter').style.width=Math.round(engine.composure)+'%';
 $('threat-label').textContent=tr(D[engine.threat||'quiet']);$('threat-label').dataset.threat=engine.threat||'quiet';$('touch-crouch').setAttribute('aria-pressed',String(engine.crouching));$('touch-crouch').setAttribute('aria-label',tr(D.crouch));$('crouch-label').textContent=tr(D.crouch);engine.drawMinimap($('minimap'));engine.drawMinimap($('floating-minimap'));$('return-commons').hidden=state.zone==='commons';const track=state.zone==='commons'?COMMONS.entities.find(e=>e.id===state.tracked):null;$('trail-indicator').hidden=!track;if(track){$('trail-label').textContent=entityName(track);$('trail-arrow').style.transform='rotate('+((Math.atan2(track.y-engine.player.y,track.x-engine.player.x)*180/Math.PI)+90)+'deg)';}
 $('touch-ward').disabled=engine.wardCooldown>0;$('touch-ward').textContent=engine.wardCooldown>0?String(Math.ceil(engine.wardCooldown)):'✦';
 $('touch-ward').setAttribute('aria-label',tr('ward'));$('touch-run').setAttribute('aria-label',tr('run'));
 const sec=Math.floor(state.playSeconds);$('play-clock').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');
 const near=engine.nearest();$('interaction-prompt').hidden=modalOpen||!near;
 if(near)$('interaction-prompt').querySelector('span').textContent=entityName(near);
}
function entityName(e){if(e.type==='music')return tr(MT.studio);if(e.type==='wayback')return tr(W.return);if(e.type==='portal')return tr(CHAPTERS[e.chapterIndex].name);if(e.type==='discovery')return tr(W[e.item]);if(e.type==='bell')return tr(W.bell)+' '+e.note;if(['workshop','mailbox'].includes(e.type))return tr(W[e.type]);if(e.type==='pondClue')return tr(W.melody);if(e.type==='notice')return tr(W.title);if(e.type==='episode')return tr(EPISODES[state.chapter].title);if(e.type==='station')return state.chapter===7?tr('consent')+' '+(e.slot+1):puzzleName(e.puzzle);if(e.type==='record')return tr('echo');if(e.type==='exit')return tr(state.chapter===7?'decision':'exit');return state.chapter===7?tr('decision'):tr('interact');}
function interact(entity){if(modalOpen||!playing)return;if(state.zone==='commons'){interactCommons(entity);return;}if(entity.type==='wayback'){goCommons();return;}const ch=CHAPTERS[state.chapter];audio.tone('paper');if(entity.type==='record'){if(!state.records.includes(entity.id)){state.records.push(entity.id);save();}const note=ch.records[entity.slot];openModal(root=>{root.append(h('div',{class:'modal-kicker'},tr('echo')+' · '+String(entity.slot+1).padStart(2,'0')),h('span',{class:'source-tag'},tr(note.source?'sourceLabel':'fictionLabel')),h('h2',{},tr(ch.name)),h('p',{class:'body-copy'},tr(note.body)));if(note.source){const s=SOURCES.find(s=>s.id===note.source);root.append(h('a',{href:s.url,target:'_blank',rel:'noopener noreferrer',class:'text-btn'},s.title));}root.append(h('div',{class:'modal-actions'},button(tr('next'),closeModal,'btn primary')));},{clock:false});return;}
 if(entity.type==='episode'){showEpisode();return;}
 if(entity.type==='station'){if(state.solved.includes(entity.id)){toast(tr('resolved'));return;}showPuzzle(entity);return;}
 if(entity.type==='npc'){if(ch.index===7)showEndingChoices();else{openModal(root=>{const portrait=h('canvas',{width:46,height:52,class:'portrait','aria-hidden':'true'}),c=portrait.getContext('2d');character(c,23,45,{kind:entity.kind,scale:1.3});root.append(h('div',{class:'speaker'},portrait,h('span',{},ch.index===0||ch.index===5?'MINA':ch.index===4?'SATOSHI · FICTION':'ARCHIVE')),h('h2',{},tr(ch.name)),h('p',{class:'body-copy'},tr(ch.intro)),h('div',{class:'modal-actions'},button(tr('next'),closeModal,'btn primary')));},{clock:false});}return;}
 if(entity.type==='exit'){if(ch.index===7){showEndingChoices();return;}if(!chapterDone(state,ch.index)){goCommons();return;}if(state.decisions[ch.index]===undefined)showDecision();else goCommons();}
}
function showPuzzle(station){const captured=state;openModal(root=>{if((captured.puzzleProgress[station.id]||0)>=(station.rounds||2)){completeStation(station);return;}puzzle=new PuzzleUI({state:captured,station,container:root,audio,onSave:save,onComplete:()=>{if(captured===state)completeStation(station);}});puzzle.render();},{clock:false});}
function completeStation(station){if(!state.solved.includes(station.id))state.solved.push(station.id);state.puzzleProgress[station.id]=station.rounds||2;save();const chapter=CHAPTERS[state.chapter];openModal(root=>{root.append(h('div',{class:'success-mark'},'✓'),tnode('div','completed','modal-kicker'),h('h2',{},state.chapter===7?tr('consent'):puzzleName(station.puzzle)),h('p',{class:'body-copy'},tr(chapter.records[station.slot].body)));if(state.chapter===7)root.append(h('p',{class:'modal-note'},tr('consent')));root.append(h('div',{class:'modal-actions'},button(tr('next'),closeModal,'btn primary')));},{clock:false});audio.tone('success');}
function showDecision(){const ch=CHAPTERS[state.chapter];openModal(root=>{root.append(tnode('div','decision','modal-kicker'),h('h2',{},tr(ch.name)),tnode('p','choiceNote','body-copy'));const list=h('div',{class:'choice-list'});ch.choices.forEach((choice,index)=>list.append(button('',()=>confirmDecision(ch,index),'choice',{'data-choice':index})));[...list.children].forEach((el,i)=>el.append(h('strong',{},h('span',{},tr(ch.choices[i].text)),h('span',{class:'choice-no'},String(i+1).padStart(2,'0')))));root.append(list);},{clock:false});}
function confirmDecision(ch,index){openModal(root=>root.append(tnode('div','decision','modal-kicker'),h('h2',{},tr(ch.name)),h('p',{class:'body-copy'},tr(ch.choices[index].text)),h('div',{class:'modal-actions'},button(tr('back'),showDecision),button(tr('confirm'),()=>{if(state.chapter!==ch.index)return;addDecision(state,ch.index,index);save();closeModal();goCommons();toast(tr(W.completed));},'btn primary'))),{clock:false});}
function showEndingChoices(){openModal(root=>renderEndingOffers(root,{state,onChoose:confirmEnding,onExplore:closeModal,onGallery:showGallery}),{clock:false});}
function confirmEnding(ending){openModal(root=>root.append(tnode('div','decision','modal-kicker'),h('h2',{},tr(ending.name)),h('p',{class:'body-copy'},tr(ending.offer)),h('div',{class:'modal-actions'},button(tr('back'),()=>state.chapter===7?showEndingChoices():showPause()),button(tr('confirm'),()=>{if(!recordEnding(state,ending.id))return;save();showEnding(ending.id);},'btn primary'))),{clock:false});}
function showEnding(id){const ending=ENDINGS.find(e=>e.id===id);if(!ending)return;const counts=reflectionCounts(state),afterword=id==='repayment'?tr(AFTERMATH[state.decisions[0]===0||state.microDecisions[0]===0?'acknowledged':'unanswered']):id==='fire'?tr(AFTERMATH[(counts.evidence||0)>=2?'copies':'missing']):null;openModal(root=>renderFinale(root,{ending,state,afterword,onReflection:showReflection,onReplay:replayFinalChoice,onMenu:titleScreen,onGallery:showGallery}),{clock:true});audio.chapter(ENDING_ROUTES[id].music);}
function replayFinalChoice(){if(!resumeBeforeEnding(state))return;save();closeModal();loadChapter(false);if(state.chapter===7&&state.zone==='chapter')showEndingChoices();}
function showReflection(){openModal(root=>renderReflection(root,{state,onSave:save,onBack:()=>showEnding(state.ending),onSaved:()=>toast(tr('reflectionSaved'))}),{clock:true});}
function showGallery(){openModal(root=>renderEndingGallery(root,{state}));}

function showEpisode(){const index=state.chapter,existing=state.microDecisions[index];openModal(root=>{episodeUI=new EpisodeUI({episode:EPISODES[index],container:root,settings,audio,existing,onComplete:option=>{if(addEpisodeDecision(state,index,option)){save();audio.tone('success');}showEpisode();}});episodeUI.render();if(existing!==undefined)root.append(h('div',{class:'modal-actions'},button(tr('next'),closeModal,'btn primary')));},{clock:false});}
function showJournal(tab='records'){openModal(root=>{root.append(tnode('div','footer','modal-kicker'),tnode('h2','journal'));const tabs=h('div',{class:'journal-tabs',role:'tablist'});for(const k of ['records','decisions','sources'])tabs.append(button(tr(k),()=>showJournal(k),k===tab?'active':'',{role:'tab','aria-selected':tab===k}));root.append(tabs);if(tab==='records'){if(!state.records.length)root.append(tnode('p','emptyJournal','body-copy'));for(const id of [...state.records].sort()){const[index,n]=id.split(':r').map(Number),ch=CHAPTERS[index],note=ch.records[n];root.append(h('div',{class:'journal-entry'},h('h3',{},tr(ch.name)+' / '+(n+1)),h('p',{},tr(note.body)),h('small',{},tr(note.source?'sourceLabel':'fictionLabel'))));}}else if(tab==='decisions'){if(!decisionEvents(state).length)root.append(tnode('p','emptyJournal'));for(const event of decisionEvents(state))root.append(h('div',{class:'journal-entry'},h('h3',{},tr(event.title)),h('p',{},tr(event.text))));}else{root.append(tnode('p','aboutBody','body-copy'));for(const s of SOURCES)root.append(h('div',{class:'journal-entry'},h('a',{href:s.url,target:'_blank',rel:'noopener noreferrer'},s.title)));}},{clock:true});}
function showMap(){openModal(root=>renderAtlas(root,{state,onVisit:visitMemory,onTrack:id=>{state.tracked=id;save();closeModal();toast(tr(W.trail));},onReturn:goCommons}),{clock:true});}
function visitMemory(index){if(!canVisitChapter(state,index)){toast(tr(W.finalLock));return;}if(!enterChapter(state,index))return;closeModal();loadChapter();}
function goCommons(){returnToCommons(state);closeModal();loadChapter(false);}
function commonsMessage(title,body,action){openModal(root=>{root.append(h('div',{class:'modal-kicker'},tr(W.optional)),h('h2',{},tr(title)),h('p',{class:'body-copy'},tr(body)));if(action)root.append(h('div',{class:'modal-actions'},button(tr(action.label),action.run,'btn primary')));else root.append(h('div',{class:'modal-actions'},button(tr('next'),closeModal,'btn primary')));},{clock:false});}
function interactCommons(entity){audio.tone('paper');if(entity.type==='music'){showMusic();return;}if(entity.type==='portal'){visitMemory(entity.chapterIndex);return;}if(entity.type==='notice'){showMap();return;}if(entity.type==='discovery'){if(discover(state,entity.id)){save();audio.tone('success');}if(entity.item==='postcard')commonsMessage(W.postcard,POSTCARDS[entity.slot]);else toast(tr(W.fuse)+' · '+projectCount(state,'fuse')+'/3');updateHUD();return;}if(entity.type==='pondClue'){commonsMessage(W.melody,W.bellHint);return;}if(entity.type==='bell'){const completed=ringBell(state,entity.note);audio.bell(entity.note);save();if(completed)commonsMessage(W.melody,W.bellDone);else toast(tr(W.melody)+' · '+state.bellSequence.length+'/4');hudSignature='';updateHUD();return;}if(entity.type==='workshop'||entity.type==='mailbox'){const lamps=entity.type==='workshop',id=lamps?'lights':'letters',done=state.projects.includes(id),ready=projectCount(state,lamps?'fuse':'postcard')===3;commonsMessage(lamps?W.workshop:W.mailbox,done?(lamps?W.workshopDone:W.mailboxDone):(lamps?W.workshopNeed:W.mailboxNeed),!done&&ready?{label:lamps?W.repair:W.deliver,run:()=>{finishProject(state,id);save();engine.refreshScenery();audio.tone('success');commonsMessage(lamps?W.workshop:W.mailbox,lamps?W.workshopDone:W.mailboxDone);}}:null);}}
function showPause(){if(!playing)return;openModal(root=>root.append(tnode('div','edition','modal-kicker'),tnode('h2','pauseTitle'),tnode('p','pauseBody','body-copy'),h('div',{class:'choice-list'},button(tr('continue'),closeModal,'btn primary'),button(tr('settings'),showSettings),button(tr(W.return),goCommons),button(tr('export'),exportSave),button(tr(D.gallery),showGallery),button(tr(MT.title),showMusic),button(tr(ENDINGS[4].name),()=>confirmEnding(ENDINGS[4])),button(tr('mainMenu'),titleScreen))),{clock:true});}
function settingsRow(title,desc,control){return h('label',{class:'settings-row'},h('span',{},tr(title),desc?h('small',{},tr(desc)):null),control);}
function showSettings(){openModal(root=>{root.append(tnode('div','edition','modal-kicker'),tnode('h2','settings'));const lang=h('select',{'aria-label':tr('language'),onChange:()=>{settings.language=lang.value;storeSettings();translate();showSettings();}});for(const l of LANGUAGES)lang.append(h('option',{value:l.id},l.name));lang.value=settings.language;root.append(settingsRow('language',null,lang));const sound=h('input',{type:'checkbox',checked:settings.sound,onChange:()=>{settings.sound=sound.checked;audio.set(settings.sound,settings.volume);storeSettings();translate();}});root.append(settingsRow('sound','soundDesc',sound));const volume=h('input',{type:'range',min:0,max:1,step:.05,value:settings.volume,'aria-label':tr('sound'),onInput:()=>{settings.volume=Number(volume.value);audio.set(settings.sound,settings.volume);storeSettings();}});root.append(settingsRow('sound',null,volume));const quality=h('select',{'aria-label':tr('quality'),onChange:()=>{settings.quality=quality.value;storeSettings();}});for(const value of ['auto','high','low'])quality.append(h('option',{value},tr(value)));quality.value=settings.quality;root.append(settingsRow('quality',null,quality));const horror=h('select',{'aria-label':tr(D.horror),onChange:()=>{settings.horror=horror.value;storeSettings();}});for(const value of ['mild','cinematic'])horror.append(h('option',{value},tr(D[value])));horror.value=settings.horror;root.append(settingsRow(D.horror,D.horrorHelp,horror));const veil=h('input',{type:'checkbox',checked:settings.pixelVeil,onChange:()=>{settings.pixelVeil=veil.checked;storeSettings();}});root.append(settingsRow(D.mosaic,null,veil));for(const [key,title,desc]of [['reducedMotion','motion',null],['calm','calm','calmDesc']]){const input=h('input',{type:'checkbox',checked:settings[key],onChange:()=>{settings[key]=input.checked;storeSettings();translate();}});root.append(settingsRow(title,desc,input));}const size=h('select',{'aria-label':tr('textSize'),onChange:()=>{settings.textSize=Number(size.value);storeSettings();translate();}});for(const value of [1,1.1,1.2])size.append(h('option',{value},Math.round(value*100)+'%'));size.value=settings.textSize;root.append(settingsRow('textSize',null,size));root.append(h('div',{class:'modal-actions'},button(tr('export'),exportSave,'btn secondary',{disabled:!state}),button(tr('import'),importSave),button(tr('next'),closeModal,'btn primary')));},{clock:true});}
function showMusic(){openModal(root=>{musicUI=new MusicUI({container:root,audio,settings,onSettings:storeSettings,onToggle:()=>{settings.sound=!settings.sound;audio.set(settings.sound,settings.volume);storeSettings();translate();},onSaved:()=>toast(tr(MT.saved))});},{clock:true});}
function exportSave(){if(!state)return;save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=h('a',{href:url,download:'last-buyer-save.json'});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importSave(){const input=h('input',{type:'file',accept:'.json,application/json'});input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;if(file.size>200000){toast(tr('invalidSave'));return;}try{const candidate=validateState(JSON.parse(await file.text()));if(!candidate){toast(tr('invalidSave'));return;}openModal(root=>root.append(tnode('h2','import'),tnode('p','overwrite','body-copy'),h('div',{class:'modal-actions'},button(tr('cancel'),closeModal),button(tr('confirm'),()=>{state=candidate;session++;closeModal();save();enterGame();loadChapter(false);if(state.ending)showEnding(state.ending);toast(tr('restore'));},'btn primary'))));}catch{toast(tr('invalidSave'));}});input.click();}
let lastClock=performance.now(),saveClock=0;setInterval(()=>{const now=performance.now(),dt=Math.min(1.5,(now-lastClock)/1000);lastClock=now;if(playing&&state&&!document.hidden&&!clockPaused){state.playSeconds+=dt;saveClock+=dt;if(saveClock>10){save();saveClock=0;}}if(playing)updateHUD();},500);
function animateTitle(now){requestAnimationFrame(animateTitle);if(playing||document.hidden||now-titleLast<80)return;titleLast=now;drawTitle($('title-canvas').getContext('2d',{alpha:false}),now/1000,settings.reducedMotion);}
translate();$('continue-game').hidden=!state;requestAnimationFrame(animateTitle);
