import {L} from './i18n.js';
export const MOBILE={
 title:L('گوشی را افقی بگیر','Turn your phone sideways','请横握手机','أدر هاتفك أفقياً','Gira tu teléfono','फ़ोन को आड़ा करें','Tournez votre téléphone','Vire o celular'),
 body:L('شهر در حالت افقی جا باز می‌کند. بازی تا آماده‌شدنت متوقف است؛ پیشرفتت محفوظ می‌ماند.','The city has more room in landscape. Your game is paused here until you are ready.','横屏让城市拥有更多空间。准备好之前，游戏会在此暂停。','تتسع المدينة في الوضع الأفقي. تتوقف اللعبة هنا حتى تكون مستعداً.','La ciudad tiene más espacio en horizontal. El juego está pausado hasta que estés listo.','आड़े दृश्य में शहर के लिए अधिक जगह है। तैयार होने तक खेल यहीं रुका है।','La ville a plus de place en paysage. Le jeu reste en pause jusqu’à ce que vous soyez prêt.','A cidade tem mais espaço na horizontal. O jogo fica pausado até você estar pronto.'),
 enter:L('نمایش افقی و تمام‌صفحه','Landscape & fullscreen','横屏与全屏','أفقي وملء الشاشة','Horizontal y pantalla completa','आड़ा और पूर्ण स्क्रीन','Paysage et plein écran','Horizontal e tela cheia'),
 manual:L('اگر صفحه نچرخید، گوشی را خودت بچرخان. مرورگر ممکن است چرخش خودکار را پشتیبانی نکند.','If the view stays upright, rotate your phone by hand. Your browser may not support automatic rotation.','如果仍是竖屏，请手动旋转手机。浏览器可能不支持自动旋转。','إذا بقيت الشاشة عمودية، أدر هاتفك يدوياً. قد لا يدعم المتصفح الدوران التلقائي.','Si sigue vertical, gira el teléfono a mano. El navegador puede no admitir el giro automático.','दृश्य सीधा रहे तो फ़ोन हाथ से घुमाएँ। ब्राउज़र में स्वतः घुमाना संभव न हो सकता है।','Si la vue reste verticale, tournez le téléphone à la main. Le navigateur peut ne pas gérer la rotation automatique.','Se continuar vertical, gire o celular à mão. O navegador pode não permitir a rotação automática.'),
 portrait:L('ادامه در حالت عمودی','Continue in portrait','继续使用竖屏','المتابعة عمودياً','Continuar en vertical','सीधे दृश्य में जारी रखें','Continuer en portrait','Continuar na vertical'),
 checking:L('در حال تغییر نمایش…','Changing the display…','正在调整显示……','جارٍ تغيير العرض…','Cambiando la pantalla…','दृश्य बदला जा रहा है…','Changement d’affichage…','Mudando a tela…')
};
