import {G} from './guidance-text.js';
import {h,button} from './dom.js';
import {tr,direction} from './i18n.js';
import {hash} from './art.js';
import {generateCircuit,circuitStatus,rotateMask,generateLights,toggleLights,generateSequence,generateLedger,generateCode} from './puzzles.js';
const NAME={circuit:'puzzleCircuit',memory:'puzzleMemory',ledger:'puzzleLedger',lights:'puzzleLights',code:'puzzleCode'};
export const puzzleName=type=>tr(NAME[type]);
export class PuzzleUI{
 constructor({state,station,container,onSave,onComplete,audio}){this.state=state;this.station=station;this.container=container;this.onSave=onSave;this.onComplete=onComplete;this.audio=audio;this.round=state.puzzleProgress[station.id]||0;this.help=false;this.feedback='';this.locked=false;this.total=station.rounds||2;this.initRound();}
 initRound(){const type=this.station.puzzle,seed=hash(this.station.id+':'+this.round+':last-buyer');this.feedback='';this.locked=false;this.help=false;this.entered=[];this.matches=[];this.selected=null;this.ready=false;this.moves=new Set();this.digits=[0,0,0,0];if(type==='circuit')this.data=generateCircuit(4+this.round,seed);if(type==='lights')this.data=generateLights(this.round===0?3:4,seed);if(type==='memory')this.data=generateSequence(4+this.round*2,seed);if(type==='ledger')this.data=generateLedger(4+this.round,seed);if(type==='code')this.data=generateCode(this.round,seed);}
 dispose(){clearTimeout(this.timer);this.disposed=true;}
 render(){if(this.disposed)return;const focus=document.activeElement?.getAttribute('data-focus'),root=this.container;root.replaceChildren();const type=this.station.puzzle;root.append(h('div',{class:'modal-kicker'},tr('round',{n:this.round+1,total:this.total})),h('h2',{},puzzleName(type)),h('p',{class:'body-copy'},tr(type+'Help')));const area=h('div',{class:'puzzle-area',dir:'ltr','data-puzzle':type});root.append(area);
  if(type==='circuit')this.circuit(area);if(type==='lights')this.lights(area);if(type==='memory')this.memory(area);if(type==='ledger')this.ledger(area);if(type==='code')this.code(area);
  root.append(h('p',{class:'puzzle-feedback',role:'status','aria-live':'polite'},this.feedback));
  if(this.help){root.append(h('p',{class:'modal-note'},tr('assistNote')));if(type==='lights'){const needed=new Set(this.data.solution);for(const i of this.moves){if(needed.has(i))needed.delete(i);else needed.add(i);}root.append(h('p',{class:'puzzle-feedback',dir:'ltr'},[...needed].map(i=>i+1).join(' → ')));}root.append(button(tr('assist'),()=>this.assist(),'btn secondary',{'data-focus':'assist',disabled:this.locked}));}
  root.append(h('div',{class:'modal-actions'},button(tr('fullHint'),()=>{this.help=!this.help;this.render();},'text-btn',{'data-focus':'hint'})));
  if(focus)root.querySelector(`[data-focus="${CSS.escape(focus)}"]`)?.focus({preventScroll:true});
 }
 circuit(area){const{size,tiles,solution}=this.data,status=circuitStatus(tiles,size),grid=h('div',{class:'circuit-grid',style:`grid-template-columns:repeat(${size},1fr)`});tiles.forEach((mask,i)=>{const lit=status.reached.has(i);const cell=button('',()=>{if(this.locked)return;tiles[i]=rotateMask(tiles[i]);this.audio.tone('click');if(circuitStatus(tiles,size).solved)this.winRound();this.render();},`circuit-tile ${lit?'lit':''} ${i===0?'source':''} ${i===tiles.length-1?'sink':''}`,{'aria-label':`${i+1}: ${[mask&1?'↑':'',mask&2?'→':'',mask&4?'↓':'',mask&8?'←':''].join('')}`,'data-focus':`tile-${i}`,disabled:this.locked});const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 64 64');const color=lit?'#b7f578':'#647d73';for(const[bit,x,y]of[[1,32,0],[2,64,32],[4,32,64],[8,0,32]]){if(!(mask&bit))continue;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M32 32L${x} ${y}`);path.setAttribute('stroke',color);path.setAttribute('stroke-width','7');path.setAttribute('fill','none');svg.append(path);}const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx','32');dot.setAttribute('cy','32');dot.setAttribute('r','5');dot.setAttribute('fill',color);svg.append(dot);cell.append(svg);if(this.help&&mask!==solution[i])cell.style.outline='1px solid #dba765';grid.append(cell);});area.append(grid);}
 lights(area){const{size,board}=this.data,grid=h('div',{class:'circuit-grid',style:`grid-template-columns:repeat(${size},1fr)`});board.forEach((value,i)=>{const b=button(value?'●':'○',()=>{if(this.locked)return;toggleLights(board,size,i);if(this.moves.has(i))this.moves.delete(i);else this.moves.add(i);this.audio.tone('click');if(board.every(Boolean))this.winRound();this.render();},'circuit-tile '+(value?'lit':''),{'aria-label':`${i+1}: ${value?'●':'○'}`,'aria-pressed':Boolean(value),'data-focus':`tile-${i}`,disabled:this.locked});b.style.minHeight='50px';b.style.color=value?'#d4f5a1':'#536b5d';b.style.fontSize='24px';grid.append(b);});area.append(grid);}
 memory(area){const display=h('div',{class:'sequence-display',dir:'ltr'});this.data.forEach((n,i)=>display.append(h('span',{class:this.entered.length>i?'active':''},!this.ready||this.help?n+1:this.entered.length>i?n+1:'·')));area.append(display);if(!this.ready){area.append(button(tr('ready'),()=>{this.ready=true;this.entered=[];this.render();},'btn primary',{'data-focus':'ready'}));return;}const grid=h('div',{class:'sequence-pad'});for(let i=0;i<9;i++)grid.append(button(String(i+1),()=>{if(this.locked)return;if(this.data[this.entered.length]!==i){this.audio.tone('error');this.feedback=tr('tryAgain');this.entered=[];}else{this.feedback='';this.entered.push(i);this.audio.tone('click');if(this.entered.length===this.data.length)this.winRound();}this.render();},'',{'data-focus':`key-${i}`,disabled:this.locked}));area.append(grid,button(tr('replay'),()=>{this.ready=false;this.entered=[];this.render();},'text-btn',{'data-focus':'replay',disabled:this.locked}));}
 ledger(area){const board=h('div',{class:'ledger-board',dir:'ltr'}),left=h('div',{class:'ledger-column'}),right=h('div',{class:'ledger-column'});for(const item of this.data.left){const matched=this.matches.includes(item.id);left.append(button(`${item.symbol} ${item.a} + ${item.b}`,()=>{this.selected=item.id;this.feedback='';this.render();},`ledger-card ${matched?'matched':''} ${this.selected===item.id?'selected':''}`,{'data-focus':`left-${item.id}`,disabled:matched||this.locked}));}for(const item of this.data.right){const matched=this.matches.includes(item.id);right.append(button(`${item.symbol} ${item.value}`,()=>{if(this.selected===null)return;if(this.selected===item.id){this.matches.push(item.id);this.selected=null;this.audio.tone('click');if(this.matches.length===this.data.left.length)this.winRound();}else{this.feedback=tr('tryAgain');this.audio.tone('error');}this.render();},'ledger-card '+(matched?'matched':''),{'data-focus':`right-${item.id}`,disabled:matched||this.locked}));}board.append(left,right);area.append(board);}
 code(area){
  const hintKey=['codeClue','codeClue2','codeClue3'][this.round],parts=tr(hintKey,{code:'{digits}'}).split('{digits}');
  const digits=h('bdi',{class:'code-sequence',dir:'ltr','data-code-clue':'true','aria-label':this.data.digits.join(' ')});
  this.data.digits.forEach((n,i)=>{if(i)digits.append(h('span',{'aria-hidden':'true'},' · '));digits.append(h('span',{'data-digit-index':i},String(n)));});
  area.append(h('p',{class:'modal-note code-clue',dir:direction()},parts[0],digits,parts[1]||''),h('p',{class:'code-order',dir:direction()},tr(G.digits)));
  const row=h('div',{class:'dial-row',dir:'ltr'});
  this.digits.forEach((n,i)=>{
   const label=tr(G.slot,{n:i+1});
   row.append(h('div',{class:'dial','data-dial-index':i},h('small',{class:'dial-label',dir:direction()},label),button('▲',()=>{this.digits[i]=(n+1)%10;this.render();},'',{'data-focus':'up-'+i,'aria-label':label+' +1',disabled:this.locked}),h('output',{dir:'ltr','aria-label':label},n),button('▼',()=>{this.digits[i]=(n+9)%10;this.render();},'',{'data-focus':'down-'+i,'aria-label':label+' −1',disabled:this.locked})));
  });
  area.append(row,button(tr('check'),()=>{if(this.digits.every((v,i)=>v===this.data.solution[i]))this.winRound();else{this.feedback=tr('tryAgain');this.audio.tone('error');}this.render();},'btn primary',{'data-focus':'check',disabled:this.locked}));
  if(this.help)area.append(h('p',{dir:'ltr',class:'puzzle-feedback code-answer'},this.data.solution.join(' · ')));
 }

 assist(){if(this.locked)return;this.winRound();this.render();}
 winRound(){if(this.locked||this.disposed)return;this.locked=true;this.audio.tone('success');this.feedback=tr('completed');const next=this.round+1;this.state.puzzleProgress[this.station.id]=next;this.onSave();this.timer=setTimeout(()=>{if(this.disposed)return;if(next>=this.total)this.onComplete();else{this.round=next;this.initRound();this.render();}},500);}
}
