import {L,ORDER} from './i18n.js';

const q=(...values)=>L(...values);
const localize=values=>Object.fromEntries(ORDER.map((lang,index)=>[lang,values[index]??values[1]??'']));

export const V={
 title:q('روستای مه‌آلود','THE MISTWOOD VILLAGE','雾林村','قرية الغابة الضبابية','PUEBLO DEL BOSQUE NEBLINOSO','धुंधवन गाँव','VILLAGE DE LA FORÊT BRUMEUSE','VILA DA FLORESTA NEBULOSA'),
 intro:q('پشت جادهٔ آرشیو، روستایی در دل جنگل است. ولاد با مینا در مغازه کار می‌کند؛ ماشین براق، عشق و آینده را برای فروش می‌آورد.','Beyond the archive road, a forest village asks Vlad to choose between Mina, money, family and tomorrow.','档案公路之外，森林村庄让弗拉德在米娜、金钱、家人与明天之间选择。','خلف طريق الأرشيف قرية في الغابة؛ على ولاد الاختيار بين مينا والمال والعائلة والغد.','Más allá del archivo, un pueblo del bosque obliga a Vlad a elegir entre Mina, dinero, familia y mañana.','अभिलेख की सड़क के पार जंगल का गाँव व्लाद से मीना, पैसे, परिवार और कल में चुनाव माँगता है।','Au-delà des archives, un village forestier demande à Vlad de choisir entre Mina, l’argent, la famille et demain.','Além do arquivo, uma vila na floresta pede que Vlad escolha entre Mina, dinheiro, família e amanhã.'),
 money:q('پول روستا','Village cash','村庄现金','نقود القرية','Dinero del pueblo','गाँव की नकदी','Caisse du village','Dinheiro da vila'), reputation:q('اعتبار','Reputation','声望','السمعة','Reputación','प्रतिष्ठा','Réputation','Reputação'), bond:q('پیوند با مینا','Bond with Mina','与米娜的羁绊','رابطة مينا','Vínculo con Mina','मीना से बंधन','Lien avec Mina','Laço com Mina'), growth:q('رشد روستا','Village growth','村庄发展','نمو القرية','Crecimiento','गाँव का विकास','Croissance','Crescimento'), vehicle:q('وسیلهٔ رفت‌وآمد','Ride','交通工具','وسيلة النقل','Vehículo','सवारी','Véhicule','Veículo'), weapon:q('ابزار دفاع','Self-defense','自卫工具','أداة دفاع','Defensa','आत्मरक्षा','Défense','Defesa'),
 buy:q('BUY BUTTON · انتخاب کن','BUY BUTTON · CHOOSE','BUY BUTTON · 选择','BUY BUTTON · اختر','BUY BUTTON · ELIGE','BUY BUTTON · चुनें','BUY BUTTON · CHOISIR','BUY BUTTON · ESCOLHA'), shop:q('مغازهٔ روستا','Village shop','村庄商店','متجر القرية','Tienda','गाँव की दुकान','Boutique','Loja'), work:q('شیفت مغازه','Work a shift','工作一班','اعمل وردية','Trabajar','एक शिफ्ट','Travailler','Trabalhar'),
 workBody:q('هر سفارش یک Buy دارد؛ این بار پولش به صندوق روستا می‌رود.','Every order has a Buy button; this time the money enters the village fund.','每份订单都有 Buy；这次钱进入村庄基金。','لكل طلب زر Buy؛ هذه المرة يذهب المال لصندوق القرية.','Cada pedido tiene Buy; el dinero va al fondo.','हर आदेश में Buy है; पैसा गाँव के कोष में जाएगा।','Chaque commande a Buy ; l’argent va au fonds.','Cada pedido tem Buy; o dinheiro vai para o fundo.'), mina:q('مینا، شریک مغازه','Mina, shop partner','米娜，店铺伙伴','مينا، شريكة المتجر','Mina, socia','मीना, साथी','Mina, partenaire','Mina, parceira'), richBoy:q('پسرِ ماشین‌دار','The rich boy','开豪车的男孩','الفتى الثري','El chico rico','अमीर लड़का','Le garçon riche','O rapaz rico'),
 richBody:q('ماشین گران‌قیمت می‌رسد؛ او می‌خواهد مینا و سهم روستا را با یک Buy Button بخرد.','A polished car arrives; he wants Mina and the village share with one Buy Button.','豪车到来；他想用一个 Buy Button 买走米娜和村庄份额。','تصل سيارة فاخرة؛ يريد شراء مينا وحصة القرية بزر Buy واحد.','Llega un coche: quiere comprar a Mina y al pueblo con un Buy Button.','चमकीली कार आती है; वह एक Buy Button से मीना और गाँव खरीदना चाहता है।','Une voiture arrive : il veut acheter Mina et la part du village avec Buy.','Um carro chega: ele quer comprar Mina e a parte da vila com Buy.'), board:q('تابلوی کارهای روستا','Village board','村庄公告板','لوحة القرية','Tablón','गाँव का बोर्ड','Panneau','Quadro'), boardBody:q('چراغ، پل، بازار و درمانگاه؛ چهار راه برای رشد بدون فروختن روستا.','Lamps, bridge, market and clinic: four ways to grow without selling the village.','灯、桥、市场与诊所：发展村庄但不出售它。','الأنوار والجسر والسوق والعيادة: نمو بلا بيع القرية.','Luces, puente, mercado y clínica: crecer sin vender el pueblo.','रोशनी, पुल, बाज़ार और क्लिनिक: गाँव बेचकर नहीं, बनाकर बढ़े।','Lampes, pont, marché et clinique : grandir sans vendre le village.','Luzes, ponte, mercado e clínica: crescer sem vender a vila.'),
 yard:q('حیاط وسایل نقلیه','Vehicle yard','车辆场','ساحة المركبات','Patio de vehículos','वाहन आँगन','Cour des véhicules','Pátio'), weaponShop:q('دفاع و ابزار','Defense & tools','防卫与工具','الدفاع والأدوات','Defensa','रक्षा','Défense','Defesa'), animal:q('حیوان روستا','Village animal','村庄动物','حيوان القرية','Animal','गाँव का जानवर','Animal','Animal'), ghost:q('جنِ جنگل','Forest ghost','森林幽灵','شبح الغابة','Fantasma','जंगल का भूत','Fantôme','Fantasma'), thief:q('دزدِ جاده','Road thief','路匪','لص الطريق','Ladrón','रास्ते का चोर','Voleur','Ladrão'), gate:q('دروازهٔ خروج','Village gate','村庄出口','بوابة القرية','Puerta','गाँव का द्वार','Porte','Portão'), forest:q('لبهٔ جنگل','Forest edge','森林边缘','حافة الغابة','Borde','जंगल का किनारा','Lisière','Borda'), protect:q('از خودت و روستا مراقبت کن.','Protect yourself and the village.','保护自己和村庄。','احم نفسك والقرية.','Protege al pueblo y a ti.','अपनी और गाँव की रक्षा करें।','Protégez-vous et le village.','Proteja você e a vila.'),
 choose:q('انتخاب آینده','Choose the future','选择未来','اختر المستقبل','Elige el futuro','भविष्य चुनें','Choisir l’avenir','Escolher o futuro'), chooseAgain:q('دوباره انتخاب کن','Choose again','再次选择','اختر مجدداً','Elegir de nuevo','फिर चुनें','Choisir encore','Escolher novamente'), leave:q('با موفقیت از روستا برو','Leave after building a future','建设后离开','غادر بعد البناء','Salir tras construir','बनाकर निकलें','Partir après bâtir','Partir após construir'), stay:q('بمان و روستا را بساز','Stay and build the village','留下建设村庄','ابق وابن القرية','Quedarte y construir','रुककर गाँव बनाएँ','Rester et bâtir','Ficar e construir'), next:q('بعدی','Next','下一步','التالي','Siguiente','आगे','Suivant','Próximo'), run:q('فرار','Run','逃跑','اهرب','Huir','भागें','Fuir','Fugir'), strike:q('ضربه','Strike','攻击','اضرب','Golpear','वार करें','Frapper','Atacar'), listen:q('گوش‌دادن','Listen','倾听','استمع','Escuchar','सुनें','Écouter','Ouvir'), light:q('چراغ را روشن کن','Light the lantern','点亮灯笼','أشعل الفانوس','Enciende','लालटेन जलाएँ','Allumer','Acender'), feed:q('غذا بده','Feed','喂食','أطعم','Dar de comer','खिलाएँ','Nourrir','Alimentar'),
 purchased:q('خرید انجام شد.','Purchase complete.','购买完成。','اكتمل الشراء.','Compra completa.','खरीद पूरी।','Achat terminé.','Compra concluída.'), needMoney:q('پول کافی نیست؛ یک شیفت دیگر کار کن.','Not enough money; work another shift.','钱不够；再工作一班。','المال غير كاف؛ اعمل وردية أخرى.','Falta dinero; trabaja otro turno.','पैसे कम हैं; एक शिफ्ट और करें।','Pas assez d’argent ; travaillez encore.','Dinheiro insuficiente; trabalhe mais.'), completed:q('این بخش از روستا بهتر شد.','This part of the village improved.','村庄这一部分变好了。','تحسن هذا الجزء من القرية.','Esta parte mejoró.','गाँव का यह हिस्सा सुधरा।','Cette partie s’est améliorée.','Esta parte melhorou.'), outcome:q('سرنوشت روستا','Village fate','村庄命运','مصير القرية','Destino','गाँव का भाग्य','Destin','Destino'), outcomeCount:q('نتیجهٔ روستا {n} / 28','Village fate {n} / 28','村庄命运 {n} / 28','مصير القرية {n} / 28','Destino {n} / 28','भाग्य {n} / 28','Destin {n} / 28','Destino {n} / 28'), outcomeHelp:q('پایان‌ها از پول، پیوند، رشد، دفاع و واکنش تو به Buy ساخته می‌شوند.','Fates are shaped by money, bonds, growth, defense and your response to Buy.','结局由金钱、羁绊、发展、防卫与对 Buy 的回应决定。','تتشكل النهايات من المال والروابط والنمو والدفاع وردك على Buy.','Los finales dependen de dinero, vínculos, crecimiento, defensa y Buy.','अंत पैसे, बंधन, विकास, रक्षा और Buy से बनते हैं।','Les fins dépendent de l’argent, des liens, du développement, de la défense et de Buy.','Os finais dependem de dinheiro, laços, crescimento, defesa e Buy.'),
 helpMina:q('به مینا کمک کن خودش انتخاب کند','Help Mina choose for herself','帮助米娜自己选择','ساعد مينا لتختار بنفسها','Ayuda a Mina a elegir','मीना को खुद चुनने दें','Aidez Mina à choisir','Ajude Mina a escolher'), acceptOffer:q('پیشنهاد را بخر','Buy the offer','买下提议','اشتر العرض','Comprar la oferta','प्रस्ताव खरीदें','Acheter l’offre','Comprar a oferta'), defendShop:q('از مغازه دفاع کن','Defend the shop','守住商店','دافع عن المتجر','Defender la tienda','दुकान बचाएँ','Défendre la boutique','Defender a loja'), encounterBody:q('راه بسته است. ابزار تو شانس را عوض می‌کند؛ تضمینی وجود ندارد.','The road is blocked. Your tool changes the odds; nothing is guaranteed.','道路被堵。工具改变胜算，但没有保证。','الطريق مغلق. أداتك تغير الاحتمالات بلا ضمان.','El camino está bloqueado; tu herramienta cambia las probabilidades.','रास्ता बंद है; औज़ार संभावना बदलता है।','La route est bloquée ; votre outil change les chances.','A estrada está bloqueada; sua ferramenta muda as chances.'), ghostBody:q('جن رسیدهای قدیمی را نگه داشته؛ گوش بده یا چراغ را روشن کن.','The ghost keeps old receipts; listen or light the lantern.','幽灵保存旧收据；倾听或点亮灯笼。','يحفظ الشبح إيصالات قديمة؛ استمع أو أشعل الفانوس.','El fantasma guarda recibos; escucha o enciende la linterna.','भूत पुरानी रसीदें रखता है; सुनें या लालटेन जलाएँ।','Le fantôme garde les reçus ; écoutez ou allumez la lanterne.','O fantasma guarda recibos; ouça ou acenda a lanterna.'), thiefBody:q('دزد جلوتر است و Buy روی دستکش‌اش می‌درخشد؛ سه حرکت داری.','The thief blocks the road, Buy glowing on his glove; you get three moves.','小偷挡路，手套上的 Buy 发光；你有三次机会。','اللص يسد الطريق وزر Buy يلمع؛ لديك ثلاث حركات.','El ladrón bloquea el camino; tienes tres movimientos.','चोर रास्ता रोकता है; तीन चालें हैं।','Le voleur bloque la route ; trois mouvements.','O ladrão bloqueia a estrada; três movimentos.'), animalBody:q('حیوانات قیمت ندارند؛ غذا بدهی، مسیرت را به یاد می‌سپارند.','Animals have no price; feed them and they remember your route.','动物没有价格；喂它们，它们会记住你的路。','الحيوانات بلا سعر؛ أطعمها فتتذكر طريقك.','Los animales no tienen precio; aliméntalos y recordarán.','जानवरों की कीमत नहीं; खिलाएँ तो रास्ता याद रखेंगे।','Les animaux n’ont pas de prix ; nourrissez-les, ils se souviendront.','Animais não têm preço; alimente-os e lembrarão.'), planBody:q('پول، پیوند و رشدت نتیجه را عوض کرده‌اند. حالا آینده را انتخاب کن.','Money, bonds and growth changed the odds. Choose the future now.','金钱、羁绊与发展改变了结果。现在选择未来。','غيّر المال والروابط والنمو الاحتمالات. اختر المستقبل الآن.','Dinero, vínculos y crecimiento cambiaron las opciones. Elige ahora.','पैसा, बंधन और विकास ने संभावना बदली; अब भविष्य चुनें।','L’argent, les liens et la croissance ont changé les chances. Choisissez.','Dinheiro, laços e crescimento mudaram as chances.')
};

const project=(id,cost,name,body)=>({id,cost,growth:1,name:q(...name),body:q(...body)});
export const VILLAGE_PROJECTS=[
 project('lamps',45,['چراغ‌های جنگل','Forest lamps','森林灯','مصابيح الغابة','Luces del bosque','जंगल की बत्तियाँ','Lampes de forêt','Luzes da floresta'],['شب امن‌تر می‌شود.','Night becomes safer.','夜晚更安全。','الليل أكثر أمناً.','La noche es más segura.','रात सुरक्षित।','La nuit est plus sûre.','A noite fica segura.']),
 project('bridge',75,['پل چوبی','Wooden bridge','木桥','الجسر الخشبي','Puente de madera','लकड़ी का पुल','Pont de bois','Ponte de madeira'],['روستا به جنگل وصل می‌شود.','The village reaches the forest.','村庄连上森林。','تتصل القرية بالغابة.','El pueblo llega al bosque.','गाँव जंगल से जुड़ता है।','Le village rejoint la forêt.','A vila alcança a floresta.']),
 project('market',120,['بازار آزاد','Open market','开放市场','السوق المفتوح','Mercado abierto','खुला बाज़ार','Marché ouvert','Mercado aberto'],['Buy قیمت دارد، نه فرمان.','Buy has a price, not a command.','Buy 是价格，不是命令。','Buy سعر لا أمر.','Buy tiene precio, no orden.','Buy कीमत है, आदेश नहीं।','Buy a un prix, pas un ordre.','Buy tem preço, não ordem.']),
 project('clinic',160,['درمانگاه','Small clinic','小诊所','عيادة صغيرة','Clínica','छोटा क्लिनिक','Petite clinique','Clínica'],['هر زخم پشت دکمه نمی‌رود.','Not every wound goes behind a button.','伤口不必交给按钮。','لا جرح خلف زر.','No toda herida va tras un botón.','हर घाव बटन के पीछे नहीं।','Aucune blessure derrière un bouton.','Nenhuma ferida atrás de um botão.'])
];

const item=(id,kind,cost,power,name,body)=>({id,kind,cost,power,name:q(...name),body:q(...body)});
export const VILLAGE_ITEMS=[
 item('stick','weapon',20,1,['چوب محکم','Sturdy stick','结实木棍','عصا متين','Palo firme','मजबूत डंडा','Bâton solide','Bastão firme'],['دزد را عقب می‌زند.','Deters a thief.','能吓退小偷。','يردع اللص.','Disuade al ladrón.','चोर रुकता है।','Dissuade un voleur.','Afasta um ladrão.']),
 item('lantern','weapon',45,2,['فانوس آبی','Blue lantern','蓝灯笼','فانوس أزرق','Linterna azul','नीली लालटेन','Lanterne bleue','Lanterna azul'],['راه جن را روشن می‌کند.','Pushes the ghost back.','逼退幽灵。','يبعد الشبح.','Ahuyenta al fantasma.','भूत पीछे हटता है।','Repousse le fantôme.','Afasta o fantasma.']),
 item('bow','weapon',90,3,['کمان کارگاه','Workshop bow','工坊弓','قوس الورشة','Arco del taller','कार्यशाला धनुष','Arc d’atelier','Arco da oficina'],['از فاصله راه باز می‌کند.','Clears a path from afar.','远处清出道路。','يفتح الطريق من بعيد.','Abre camino de lejos.','दूर से रास्ता खोलता है।','Ouvre le passage à distance.','Abre caminho de longe.']),
 item('bike','vehicle',60,0,['دوچرخه زنگ‌زده','Rusty bicycle','生锈自行车','دراجة صدئة','Bicicleta oxidada','जंग लगी साइकिल','Vélo rouillé','Bicicleta enferrujada'],['جاده کوتاه‌تر حس می‌شود.','The road feels shorter.','道路仿佛更短。','الطريق يبدو أقصر.','El camino parece corto.','रास्ता छोटा लगता है।','La route semble plus courte.','A estrada parece menor.']),
 item('motorcycle','vehicle',150,0,['موتور شبانه','Night motorcycle','夜行摩托','دراجة ليلية','Moto nocturna','रात की मोटरसाइकिल','Moto de nuit','Moto noturna'],['هم حیوانات را بیدار می‌کند هم دزدها را.','It wakes animals and thieves.','它惊醒动物，也惊动小偷。','يوقظ الحيوانات واللصوص.','Despierta animales y ladrones.','जानवर और चोर जागते हैं।','Réveille animaux et voleurs.','Acorda animais e ladrões.']),
 item('car','vehicle',350,0,['ماشین جاده','Road car','公路汽车','سيارة الطريق','Coche de carretera','सड़क की कार','Voiture de route','Carro de estrada'],['سریع است؛ می‌تواند تو را ببرد یا روستا را جا بگذارد.','Fast; it can carry you away or leave the village behind.','很快；可以带你离开，也会留下村庄。','سريعة؛ تحملك أو تترك القرية.','Rápido; puede llevarte o dejar atrás al pueblo.','तेज़; ले जा सकती है या गाँव छोड़ सकती है।','Rapide ; elle vous emporte ou laisse le village.','Rápido; leva você ou deixa a vila.'])
];

export const VILLAGE_ENTITIES=[
 {id:'village-shop',type:'villageShop',x:470,y:620},{id:'village-mina',type:'villageMina',x:535,y:620},{id:'village-rich-boy',type:'richBoy',x:300,y:171},{id:'village-board',type:'villageBoard',x:590,y:590},{id:'buy-kiosk',type:'buyKiosk',x:1125,y:622},{id:'vehicle-yard',type:'vehicleYard',x:1450,y:775},{id:'weapon-shop',type:'weaponShop',x:1540,y:890},{id:'village-gate',type:'villageGate',x:1780,y:1120},{id:'forest-shrine',type:'forestShrine',x:1680,y:390},{id:'forest-ghost',type:'ghost',x:1690,y:475},{id:'road-thief',type:'thief',x:1305,y:500},
 ...[[312,721,'goat'],[390,748,'chicken'],[515,835,'dog'],[1220,445,'deer']].map(([x,y,kind],slot)=>({id:`village-animal-${slot}`,type:'animal',x,y,kind,slot}))
];

const families=[
 ['الطریق الأخضر','The green road','绿色道路','الطريق الأخضر','Camino verde','हरी राह','Route verte','Estrada verde','ولاد روستا را ساخت، مینا را از نو انتخاب کرد و Buy را از مالکیت جدا کرد.','Vlad built the village, chose Mina, and separated Buy from ownership.','弗拉德建设村庄，选择米娜，让 Buy 与所有权分开。','بنى ولاد القرية واختار مينا وفصل Buy عن الملكية.','Vlad construyó, eligió a Mina y separó Buy de la propiedad.','व्लाद ने गाँव बनाया, मीना चुनी और Buy को मालिकाना से अलग किया।','Vlad bâtit, choisit Mina et sépara Buy de la propriété.','Vlad construiu, escolheu Mina e separou Buy da posse.'],
 ['ریشه‌های تازه','New roots','新根','جذور جديدة','Raíces nuevas','नई जड़ें','Nouvelles racines','Novas raízes','ولاد ماند؛ هر خرید یک رأی برای آیندهٔ روستا شد.','Vlad stayed; every purchase became a vote for the village.','弗拉德留下；每次购买都成了村庄的一票。','بقي ولاد؛ كل شراء صار صوتاً للقرية.','Vlad se quedó; cada compra fue un voto.','व्लाद रुका; हर खरीद गाँव की वोट बनी।','Vlad resta ; chaque achat devint un vote.','Vlad ficou; cada compra virou um voto.'],
 ['دکمه زیر خاک','The button under soil','土下按钮','الزر تحت التراب','Botón bajo tierra','मिट्टी का बटन','Bouton sous terre','Botão sob a terra','شب، Buy زیر ریشه‌ها روشن شد و نام مرده‌ها را صدا زد.','At night, Buy under the roots called the dead.','夜里，树根下的 Buy 呼唤死者。','ليلاً نادى Buy تحت الجذور الموتى.','De noche, Buy llamó a los muertos.','रात Buy ने मृतकों को पुकारा।','La nuit, Buy appela les morts.','À noite, Buy chamou os mortos.'],
 ['پول جاده','Road money','道路的钱','مال الطريق','Dinero de carretera','रास्ते का पैसा','Argent de route','Dinheiro da estrada','دزدها رشد روستا را دیدند؛ آخرین Buy در تاریکی باز ماند.','Thieves saw the growth; the last Buy stayed open in the dark.','小偷看见发展；最后的 Buy 留在黑暗中。','رأى اللصوص النمو؛ بقي Buy الأخير مفتوحاً في الظلام.','Los ladrones vieron el crecimiento; Buy quedó abierto.','चोरों ने विकास देखा; आख़िरी Buy खुला रहा।','Les voleurs virent la croissance ; Buy resta ouvert.','Os ladrões viram o crescimento; Buy ficou aberto.'],
 ['قرارداد براق','The polished contract','闪亮合同','العقد اللامع','Contrato brillante','चमकीला अनुबंध','Contrat brillant','Contrato brilhante','پسر پولدار همه‌چیز را ساده کرد: Buy برای مغازه، سکوت برای ولاد.','The rich boy offered one Buy for the shop and silence for Vlad.','富家子提出用一个 Buy 换商店，让弗拉德沉默。','عرض الثري Buy للمتجر والصمت لولاد.','El rico ofreció Buy por la tienda y silencio para Vlad.','अमीर ने दुकान के लिए Buy और व्लाद के लिए चुप्पी दी।','Le riche offrit Buy pour la boutique et le silence à Vlad.','O rico ofereceu Buy pela loja e silêncio a Vlad.'],
 ['نجوای جنگل','Forest whisper','森林低语','همس الغابة','Susurro del bosque','जंगल की फुसफुसाहट','Murmure de la forêt','Sussurro da floresta','جن نگهبان رسیدها بود؛ جنگل هر خرید را به یاد داشت.','The ghost guarded receipts; the forest remembered every purchase.','幽灵守护收据；森林记得每次购买。','كان الشبح حارس الإيصالات؛ الغابة تذكر كل شراء.','El fantasma guardaba recibos; el bosque recordaba.','भूत रसीदों का रक्षक था; जंगल याद रखता था।','Le fantôme gardait les reçus ; la forêt se souvenait.','O fantasma guardava recibos; a floresta lembrava.'],
 ['راه بی‌نقشه','The unmapped road','无地图的路','الطريق بلا خريطة','Camino sin mapa','बिना नक्शे की राह','Route sans carte','Estrada sem mapa','پول و عشق و یک Buy بی‌صاحب در مه ماندند.','Money, love and an ownerless Buy remained in the fog.','金钱、爱情与无主的 Buy 留在雾里。','بقي المال والحب وBuy بلا مالك في الضباب.','Dinero, amor y un Buy sin dueño quedaron en la niebla.','पैसा, प्रेम और बे-मालिक Buy धुंध में रहे।','Argent, amour et Buy sans maître restèrent dans la brume.','Dinheiro, amor e Buy sem dono ficaram na névoa.']
].map(([fa,en,zh,ar,es,hi,fr,pt,bodyFa,bodyEn,bodyZh,bodyAr,bodyEs,bodyHi,bodyFr,bodyPt])=>({title:q(fa,en,zh,ar,es,hi,fr,pt),body:q(bodyFa,bodyEn,bodyZh,bodyAr,bodyEs,bodyHi,bodyFr,bodyPt)}));
const variants=[
 q('سپیده، راه روشن بود.','At dawn, the road was clear.','黎明时道路清晰。','عند الفجر كان الطريق واضحاً.','Al amanecer, el camino estaba claro.','भोर में राह साफ़ थी।','À l’aube, la route était claire.','Ao amanhecer, a rota estava clara.'),
 q('باران آمد؛ چراغ‌ها خاموش نشدند.','Rain came; the lamps stayed lit.','下雨了，灯仍亮着。','هطل المطر وبقيت المصابيح مضاءة.','Llovió; las luces siguieron.','बारिश आई; बत्तियाँ जलती रहीं।','La pluie vint ; les lampes restèrent.','Veio chuva; as luzes ficaram acesas.'),
 q('موتور روشن شد؛ صدا دو برابر شد.','The engine started; the sound doubled.','发动机启动，声音翻倍。','اشتغل المحرك وتضاعف الصوت.','El motor arrancó; el sonido creció.','इंजन चला; आवाज़ दोगुनी हुई।','Le moteur démarra ; le son doubla.','O motor ligou; o som dobrou.'),
 q('صبح فقط یک اثر انگشت روی شیشه ماند.','By morning, one fingerprint remained.','清晨只剩一个指纹。','في الصباح بقيت بصمة واحدة.','Por la mañana quedó una huella.','सुबह एक उँगली का निशान बचा।','Au matin, une empreinte resta.','De manhã, uma impressão ficou.')
];

export const VILLAGE_OUTCOMES=families.flatMap((family,familyIndex)=>variants.map((variant,variantIndex)=>({id:`village-${familyIndex}-${variantIndex}`,icon:['✦','⚑','☍','∞','◇','☾','∴'][familyIndex],name:localize(ORDER.map(lang=>`${family.title[lang]} · ${variantIndex+1}`)),body:localize(ORDER.map(lang=>`${family.body[lang]} ${variant[lang]}`))})));
export const VILLAGE_OUTCOME_IDS=VILLAGE_OUTCOMES.map(outcome=>outcome.id);
