import {L} from './i18n.js';
export const W={
 title:L('میدانِ فردا','Tomorrow Commons','明日广场','ساحة الغد','Plaza del mañana','कल का चौक','La place de demain','Praça do amanhã'),
 subtitle:L('بیرونِ قابِ خاطره','Outside the memory frame','记忆框架之外','خارج إطار الذكرى','Fuera del recuerdo','यादों के बाहर','Hors du cadre du souvenir','Fora do quadro da memória'),
 intro:L('آرشیو سقف ندارد. خیابان‌ها به خاطره‌های زمان‌های مختلف می‌رسند؛ ترتیب سفر دست توست. سرنخِ مغازه و اتاق تسویه، همراه با دو فصل دیگر، راه بازار آخر را روشن می‌کند. می‌توانی هر وقت خواستی برگردی، چراغ‌های میدان را تعمیر کنی یا فقط کنار آب بمانی.','The archive has no roof. Its streets lead to memories from different eras; choose your own order. Resolve the shop, the clearing room and any two other chapters to reach the final market. Return whenever you like, repair the streetlights, or stay beside the water.','档案没有屋顶。街道通往不同时代的记忆，顺序由你决定。完成商店、清算室和另外任意两章即可通往最终市场。随时返回、修路灯，或在水边休息。','الأرشيف بلا سقف. شوارعه تقود لذكريات مختلفة؛ اختر ترتيبك. أكمل المتجر وغرفة التسوية وفصلين آخرين لفتح السوق الأخير. عد متى شئت أو أصلح الأنوار أو استرح قرب الماء.','El archivo no tiene techo. Elige el orden de sus recuerdos. Resuelve la tienda, la cámara de compensación y otros dos capítulos para abrir el mercado final. Vuelve cuando quieras, repara farolas o descansa junto al agua.','अभिलेख की छत नहीं। रास्ते अलग दौर की यादों तक जाते हैं; क्रम चुनें। दुकान, निपटान कक्ष और कोई दो अध्याय पूरा कर अंतिम बाज़ार खोलें। कभी भी लौटें, बत्तियाँ ठीक करें या पानी के पास रुकें।','Les rues de cette archive sans toit mènent à plusieurs époques. Choisissez l’ordre. Terminez la boutique, la compensation et deux autres chapitres pour ouvrir le marché final. Revenez librement, réparez les lampes ou reposez-vous au bord de l’eau.','O arquivo não tem teto. Escolha a ordem das memórias. Resolva a loja, a compensação e quaisquer dois capítulos para abrir o mercado final. Volte quando quiser, repare as luzes ou descanse à beira da água.'),
 return:L('بازگشت به میدان','Return to the commons','返回广场','العودة للساحة','Volver a la plaza','चौक पर लौटें','Revenir à la place','Voltar à praça'),
 explore:L('هر راهی را می‌توانی دنبال کنی','Choose a path to follow','选择想走的路','اختر طريقك','Elige tu camino','अपना रास्ता चुनें','Choisissez votre chemin','Escolha seu caminho'),
 atlas:L('نقشهٔ مسیرهای باز','Map of open paths','开放路线地图','خريطة المسارات المفتوحة','Mapa de caminos abiertos','खुले रास्तों का नक्शा','Carte des chemins ouverts','Mapa de caminhos abertos'),
 visit:L('ورود به این خاطره','Enter this memory','进入这段记忆','ادخل هذه الذكرى','Entrar en este recuerdo','इस याद में जाएँ','Entrer dans ce souvenir','Entrar nesta memória'),
 finalLock:L('برای بازار آخر: مغازه، اتاق تسویه و دو فصل دلخواه دیگر را کامل کن. بقیهٔ راه‌ها آزادند.','For the final market: finish the shop, the clearing room and any two other chapters. The other paths are open.','最终市场需要完成商店、清算室和另外任意两章。其他道路均开放。','للسوق الأخير: أكمل المتجر وغرفة التسوية وفصلين تختارهما. باقي الطرق مفتوحة.','Termina la tienda, compensación y otros dos capítulos para el mercado final. Los demás caminos están abiertos.','अंतिम बाज़ार के लिए दुकान, निपटान और कोई दो अध्याय पूरे करें। बाकी रास्ते खुले हैं।','Pour le dernier marché : terminez boutique, compensation et deux autres chapitres. Les autres voies sont ouvertes.','Para o mercado final: conclua loja, compensação e dois outros capítulos. Os demais caminhos estão abertos.'),
 completed:L('خاطره روشن شد','Memory resolved','记忆已解开','اكتملت الذكرى','Recuerdo resuelto','याद सुलझी','Souvenir résolu','Memória resolvida'),
 unvisited:L('راهی که هنوز نرفته‌ای','A path not yet taken','尚未走过的路','طريق لم تسلكه','Camino por descubrir','अनदेखा रास्ता','Chemin encore inconnu','Caminho ainda não percorrido'),
 optional:L('کشف‌های اختیاری','Optional discoveries','可选发现','اكتشافات اختيارية','Descubrimientos opcionales','वैकल्पिक खोजें','Découvertes facultatives','Descobertas opcionais'),
 tasks:L('ردهایی که دنبال می‌کنی','Trails you are following','正在追踪的线索','آثار تتبعها','Pistas que sigues','जिन निशानों का पीछा है','Pistes que vous suivez','Pistas que você segue'),
 fuse:L('فیوزِ گمشده','Lost fuse','遗失的保险丝','مصهر مفقود','Fusible perdido','खोया फ्यूज़','Fusible perdu','Fusível perdido'),
 postcard:L('کارت‌پستال مینا','Mina’s postcard','米娜的明信片','بطاقة مينا','Postal de Mina','मीना का पोस्टकार्ड','Carte de Mina','Cartão de Mina'),
 workshop:L('تعمیرگاهِ چراغ‌ها','Lamplighter’s workshop','点灯工坊','ورشة الأنوار','Taller de farolas','बत्ती की कार्यशाला','Atelier des lampes','Oficina das luzes'),
 workshopNeed:L('سه فیوز در خیابان‌ها مانده‌اند. آن‌ها را پیدا کن و به میز تعمیر برگردان؛ میدان دوباره روشن می‌شود.','Three fuses are scattered through the streets. Bring them to this workbench to light the commons again.','街道中散落着三个保险丝。带回工作台，重新照亮广场。','ثلاثة مصاهر في الشوارع. أعدها إلى الطاولة لتضيء الساحة.','Hay tres fusibles por las calles. Tráelos al banco para iluminar la plaza.','गलियों में तीन फ्यूज़ हैं। उन्हें मेज़ पर लाकर चौक फिर रोशन करें।','Trois fusibles sont dispersés dans les rues. Rapportez-les à l’établi pour éclairer la place.','Três fusíveis estão pelas ruas. Traga-os à bancada para iluminar a praça.'),
 workshopDone:L('چراغ‌ها روشن شدند. چیزی از تو خریداری نشد؛ فقط یک کار ناتمام تمام شد.','The lamps are lit. Nothing was bought from you; an unfinished job is simply done.','灯亮了。没有人购买你的什么，只是一件未完的工作完成了。','أضاءت الأنوار. لم يُشترَ منك شيء؛ اكتمل عمل ناقص.','Se encienden las farolas. Nadie te compró nada; un trabajo pendiente terminó.','बत्तियाँ जल गईं। किसी ने आपसे कुछ नहीं खरीदा; अधूरा काम पूरा हुआ।','Les lampes s’allument. Rien ne vous a été acheté ; un travail inachevé est terminé.','As luzes acendem. Nada foi comprado de você; um trabalho pendente foi concluído.'),
 mailbox:L('صندوق نامهٔ بی‌قفل','The unlocked mailbox','未上锁的信箱','صندوق الرسائل المفتوح','El buzón sin llave','बिना ताले का डाकबक्सा','La boîte sans serrure','A caixa sem tranca'),
 mailboxNeed:L('سه کارت‌پستال را پیدا کن. مینا آن‌ها را برای بردن به خانهٔ تازه کنار گذاشته بود. اینجا می‌توانی مجموعه را کامل کنی.','Find three postcards. Mina saved them for her new home. Complete the little collection here.','找到三张明信片。米娜要把它们带到新家，在这里凑齐这套小收藏。','اعثر على ثلاث بطاقات حفظتها مينا لبيتها الجديد. أكمل المجموعة هنا.','Encuentra tres postales que Mina guardó para su nueva casa. Completa la colección aquí.','तीन पोस्टकार्ड खोजें जो मीना ने नए घर के लिए रखे थे। यहाँ संग्रह पूरा करें।','Retrouvez les trois cartes que Mina gardait pour son nouveau foyer. Réunissez-les ici.','Encontre três cartões que Mina guardou para a nova casa. Complete a coleção aqui.'),
 mailboxDone:L('سه کارت کنار هم یک نشانی می‌سازند، نه یک جواب: «خانه، جایی‌ست که می‌توانی نه بگویی و هنوز جایت بماند.» درخت کنار صندوق جوانه می‌زند.','Together, the cards make an address, not an answer: “Home is where you can say no and still belong.” The tree by the mailbox begins to bloom.','三张卡拼出一个地址，而不是答案：“家是你可以说不，却仍有归属的地方。”信箱旁的树开花了。','تصنع البطاقات عنواناً: «البيت حيث تقول لا ويبقى مكانك». تزهر الشجرة قرب الصندوق.','Juntas forman una dirección: «Hogar es donde puedes decir no y seguir perteneciendo». Florece el árbol del buzón.','तीनों एक पता बनाते हैं: «घर वह है जहाँ ना कहकर भी अपनी जगह रहे।» डाकबक्से का पेड़ खिलता है।','Les cartes donnent une adresse : «Chez soi, on peut dire non et garder sa place.» L’arbre près de la boîte fleurit.','Juntos dão um endereço: “Lar é onde você pode dizer não e ainda pertencer.” A árvore junto à caixa floresce.'),
 bell:L('سنگِ آوا','Sounding stone','鸣音石','حجر النغم','Piedra sonora','स्वर पत्थर','Pierre sonore','Pedra sonora'),
 bellHint:L('روی لبهٔ حوض نوشته‌اند: ۲، ۴، ۱، ۳. چهار سنگ کنار آب را به همین ترتیب به صدا درآور.','Carved into the pond: 2, 4, 1, 3. Sound the four stones beside the water in that order.','池边刻着：2、4、1、3。按此顺序敲响水边四块石头。','على الحوض: 2، 4، 1، 3. اعزف أحجار الماء بهذا الترتيب.','El estanque dice: 2, 4, 1, 3. Toca las cuatro piedras en ese orden.','तालाब पर लिखा: 2, 4, 1, 3। चार पत्थरों को इसी क्रम में बजाएँ।','Sur le bassin : 2, 4, 1, 3. Faites sonner les quatre pierres dans cet ordre.','No lago: 2, 4, 1, 3. Toque as quatro pedras nessa ordem.'),
 bellDone:L('آب به صدا جواب می‌دهد. گربه‌ای از سایه بیرون می‌آید و در سفر همراهت می‌شود؛ نه کلیدی دارد، نه قضاوتی.','The water answers. A cat steps out of the shade and joins your journey, carrying neither a key nor a judgment.','水声回应，一只猫从阴影中走出陪你旅行。它没有钥匙，也不评判你。','يرد الماء. تخرج قطة من الظل وترافقك، بلا مفتاح ولا حكم.','El agua responde. Un gato sale de la sombra y te acompaña, sin llave ni juicio.','पानी जवाब देता है। छाया से बिल्ली आकर साथ चलती है; न चाबी, न निर्णय।','L’eau répond. Un chat sort de l’ombre et vous accompagne, sans clé ni jugement.','A água responde. Um gato sai da sombra e acompanha você, sem chave nem julgamento.'),
 melody:L('آوای حوض','The pond’s melody','池塘旋律','لحن الحوض','Melodía del estanque','तालाब की धुन','La mélodie du bassin','Melodia do lago'),
 repair:L('چراغ‌ها را تعمیر کن','Repair the lamps','修复路灯','أصلح الأنوار','Reparar farolas','बत्तियाँ ठीक करें','Réparer les lampes','Reparar as luzes'),
 deliver:L('کارت‌ها را کنار هم بگذار','Put the cards together','拼合明信片','اجمع البطاقات','Reunir las postales','कार्ड साथ रखें','Réunir les cartes','Reunir os cartões'),
 progress:L('{n} از {total}','{n} of {total}','{n} / {total}','{n} من {total}','{n} de {total}','{total} में से {n}','{n} sur {total}','{n} de {total}'),
 follow:L('روی نقشه نشان بده','Mark on the map','在地图上标记','حدد على الخريطة','Marcar en el mapa','नक्शे पर चिह्न लगाएँ','Marquer sur la carte','Marcar no mapa'),
 trail:L('ردِ انتخاب‌شده','Selected trail','已选路线','المسار المختار','Ruta elegida','चुना रास्ता','Piste choisie','Rota escolhida'),
 freeNote:L('رفتن از یک فصل پیشرفتت را پاک نمی‌کند. کشف‌های میدان، شخصیت یا پایان تو را نمره‌گذاری نمی‌کنند.','Leaving a chapter keeps your progress. Commons discoveries never score your personality or endings.','离开章节会保留进度。广场探索不会给人格或结局打分。','مغادرة الفصل تحفظ تقدمك. اكتشافات الساحة لا تقيّم شخصيتك أو نهايتك.','Salir conserva tu progreso. Los descubrimientos no puntúan tu personalidad ni finales.','अध्याय छोड़ने पर प्रगति बचती है। चौक की खोजें व्यक्तित्व या अंत को अंक नहीं देतीं।','Quitter un chapitre conserve votre progression. Les découvertes ne notent ni personnalité ni fins.','Sair de um capítulo mantém seu progresso. Descobertas não pontuam personalidade nem finais.')
};
export const POSTCARDS=[
 L('پشت تصویرِ یک دریاچه: «یادت هست دوربین خراب بود؟ تو گفتی پس باید بهتر نگاه کنیم. هنوز آن عصر را، بدون هیچ عکسی، یادم هست. — مینا»','On a lake photograph: “Remember the broken camera? You said we should look more closely. I still remember that afternoon, without a single photograph. — Mina”','湖泊照片背面：“记得坏掉的相机吗？你说那就更仔细地看吧。没有照片，我仍记得那个下午。——米娜”','خلف صورة بحيرة: «تتذكر الكاميرا المكسورة؟ قلت لننظر جيداً. ما زلت أتذكر ذلك المساء بلا صورة. — مينا»','Detrás de un lago: «¿Recuerdas la cámara rota? Dijiste que miráramos mejor. Aún recuerdo esa tarde sin ninguna foto. — Mina»','झील की तस्वीर पर: «टूटा कैमरा याद है? तुमने कहा और ध्यान से देखें। बिना तस्वीर के भी वह दोपहर याद है। — मीना»','Derrière un lac : «L’appareil cassé, tu te souviens ? Tu avais dit de mieux regarder. Je me rappelle cet après-midi sans aucune photo. — Mina»','Atrás de um lago: “Lembra da câmera quebrada? Você disse para olhar melhor. Ainda lembro daquela tarde sem foto alguma. — Mina”'),
 L('روی کارت یک اتوبوس زرد: «وقتی راه را گم کردیم، تو دنبال کوتاه‌ترین مسیر بودی. من بستنی خریدم. این یکی خاطره، به خاطر دیر رسیدن خوب شد. — مینا»','A yellow bus: “When we got lost, you searched for the shortest way. I bought ice cream. This memory became a good one because we arrived late. — Mina”','黄色巴士：“迷路时你找捷径，我买了冰淇淋。正因迟到，这次回忆才变得美好。——米娜”','حافلة صفراء: «حين تهنا بحثتَ عن أقصر طريق، واشتريتُ مثلجات. أصبحت ذكرى جميلة لأننا تأخرنا. — مينا»','Un autobús amarillo: «Perdidos, buscaste un atajo. Yo compré helado. Este recuerdo fue bueno porque llegamos tarde. — Mina»','पीली बस: «खोए तो तुमने छोटा रास्ता खोजा। मैंने आइसक्रीम ली। देर पहुँचने से ही यह याद अच्छी बनी। — मीना»','Un bus jaune : «Perdus, tu cherchais un raccourci. J’ai acheté une glace. Ce souvenir est bon parce qu’on est arrivés en retard. — Mina»','Um ônibus amarelo: “Perdidos, você buscou um atalho. Comprei sorvete. Esta lembrança ficou boa porque chegamos tarde. — Mina”'),
 L('کارت سوم سفید است. فقط نوشته: «آدرس جدید را وقتی آماده شدم می‌دهم. این‌بار برای آمدن، اول زنگ بزن. — مینا»','The third card is blank except: “I’ll give you my new address when I’m ready. This time, call before visiting. — Mina”','第三张是空白，只写着：“准备好时会给你新地址。这次来之前先打电话。——米娜”','البطاقة الثالثة بيضاء: «أعطيك عنواني حين أستعد. هذه المرة اتصل قبل الزيارة. — مينا»','La tercera está en blanco: «Daré mi dirección cuando esté lista. Esta vez llama antes de venir. — Mina»','तीसरा कार्ड खाली है: «तैयार होने पर नया पता दूँगी। इस बार आने से पहले फ़ोन करना। — मीना»','La troisième est blanche : «Je donnerai ma nouvelle adresse quand je serai prête. Appelle avant de venir, cette fois. — Mina»','O terceiro está em branco: “Darei o endereço quando estiver pronta. Desta vez, ligue antes de vir. — Mina”')
];
